import Explore from './Explore';
import {lazy,Suspense,useCallback,useEffect,useLayoutEffect,useMemo,useRef,useState} from 'react';
import {useWindowVirtualizer} from '@tanstack/react-virtual';
import {Home,Compass,Clapperboard,Bookmark,UserRound,Search,ArrowUpRight,ArrowRight,Sparkles,Download,Upload,Check,ChevronRight,RotateCw,WifiOff,Settings2,Plus,X,BookOpen,Shuffle,Sun,Moon,Globe,Atom,Palette,Landmark,Leaf,MessageCircle} from 'lucide-react';
import {usePreferences,ThemeSettings,FocusSettings} from './Preferences';
import Saved from './Saved';
import {removeSavedPost} from './collections.mjs';
import CommentsSheet from './CommentsSheet';
import {BASE,emptyState,loadContent,loadState,saveState,parseBackup} from './data';
import {nextBatch,normalize,shuffle,sharePath} from './engine.mjs';
import type {Category,Post,UserState,View} from './types';
import {Avatar,Cover,Dialog,IconButton,PostCard,Reader} from './components';
const Reels=lazy(()=>import('./Film'));const FilmPlayer=lazy(()=>import('./Film').then(m=>({default:m.FilmPlayer})));
const categories:Category[]=['Tümü','Bilim','Uzay','Sanat','Tarih','Coğrafya','Felsefe','İnanç','Doğa','Teknoloji','Spor','Gündelik','Sağlık','Soru','Finans','Edebiyat'];
const categoryIcons:Record<string,typeof Atom>={'Bilim':Atom,'Uzay':Sparkles,'Sanat':Palette,'Tarih':Landmark,'Coğrafya':Globe,'Felsefe':MessageCircle,'İnanç':Sun,'Doğa':Leaf,'Teknoloji':Settings2};
const navigation:[View,string,typeof Home][]=[['feed','Akış',Home],['explore','Keşfet',Compass],['reels','Kısa anlatımlar',Clapperboard],['saved','Kaydettiklerim',Bookmark],['profile','Benim alanım',UserRound]];
function readRoute(){const m=location.pathname.match(/\/p\/([^/]+)/);return m?{id:decodeURIComponent(m[1]),slide:Math.max(0,Number(new URLSearchParams(location.search).get('slide')||1)-1)}:null;}
interface InstallEvent extends Event{prompt:()=>Promise<void>;userChoice:Promise<{outcome:string}>;}
export default function App(){
 const {prefs,setPrefs,dark}=usePreferences();
 const [posts,setPosts]=useState<Post[]>([]),[user,setUser]=useState<UserState>(emptyState),[ready,setReady]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[view,setView]=useState<View>('feed'),[category,setCategory]=useState<Category>('Tümü'),[query,setQuery]=useState(''),[order,setOrder]=useState<string[]>([]),[route,setRoute]=useState(readRoute),[comments,setComments]=useState<Post|null>(null),[story,setStory]=useState<Post|null>(null),[toast,setToast]=useState(''),[install,setInstall]=useState<InstallEvent|null>(null),[installHelp,setInstallHelp]=useState(false),[offline,setOffline]=useState(!navigator.onLine),[shareFallback,setShareFallback]=useState(''),[newVersion,setNewVersion]=useState<ServiceWorker|null>(null);
 const seenAtStart=useRef(new Set<string>());const started=useRef(false);const userRef=useRef(user);userRef.current=user;const toastTimer=useRef<ReturnType<typeof setTimeout>>(undefined);const feedScroll=useRef(0);const importInput=useRef<HTMLInputElement>(null);
 const notify=useCallback((text:string)=>{setToast(text);clearTimeout(toastTimer.current);toastTimer.current=setTimeout(()=>setToast(''),3600);},[]);
 useEffect(()=>{let alive=true;loadState().then(s=>{if(alive){setUser(s);seenAtStart.current=new Set(s.seen);setReady(true);}});loadContent().then(p=>{if(alive){setPosts(p);setLoading(false);}}).catch(()=>{if(alive){setError('İçerikler yüklenemedi. Bağlantını kontrol edip yeniden deneyebilirsin.');setLoading(false);}});return()=>{alive=false;};},[]);
 useEffect(()=>{if(ready&&posts.length&&!started.current){started.current=true;let next=nextBatch(posts,user.seen,[],12);if(!next.length)next=shuffle(posts).slice(0,12).map(p=>p.id);setOrder(next);}},[ready,posts,user.seen]);
 useEffect(()=>{if(ready)saveState(user).catch(()=>notify('Bu tarayıcı verilerini saklayamadı. Gizli sekme yerine normal bir sekme deneyebilirsin.'));},[user,ready,notify]);
 useEffect(()=>{const pop=()=>setRoute(readRoute());const net=()=>setOffline(!navigator.onLine);const before=(e:Event)=>{e.preventDefault();setInstall(e as InstallEvent);};const installed=()=>{setInstall(null);setInstallHelp(false);notify('Learnie ana ekranına eklendi.');};window.addEventListener('popstate',pop);window.addEventListener('online',net);window.addEventListener('offline',net);window.addEventListener('beforeinstallprompt',before);window.addEventListener('appinstalled',installed);if('serviceWorker'in navigator){navigator.serviceWorker.getRegistration().then(r=>{if(!r)return;if(r.waiting)setNewVersion(r.waiting);r.addEventListener('updatefound',()=>{const sw=r.installing;sw?.addEventListener('statechange',()=>{if(sw.state==='installed'&&navigator.serviceWorker.controller)setNewVersion(sw);});});});}return()=>{window.removeEventListener('popstate',pop);window.removeEventListener('online',net);window.removeEventListener('offline',net);window.removeEventListener('beforeinstallprompt',before);window.removeEventListener('appinstalled',installed);};},[notify]);
 useEffect(()=>{if(view!=='reels')return;const previous=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=previous;};},[view]);
 const update=useCallback((fn:(s:UserState)=>UserState)=>setUser(s=>fn(s)),[]);
 const toggle=useCallback((key:'liked'|'saved',id:string)=>{if(key==='saved')notify(userRef.current.saved.includes(id)?'Gönderi kaydedilenlerden kaldırıldı.':'Kaydedildi. Kaydettiklerim bölümünde seni bekliyor.');update(s=>key==='saved'&&s.saved.includes(id)?removeSavedPost(s,id):({...s,[key]:s[key].includes(id)?s[key].filter(x=>x!==id):[...s[key],id]}));},[update,notify]);
 const toggleRead=(id:string)=>update(s=>({...s,read:s.read.includes(id)?s.read.filter(x=>x!==id):[...s.read,id]}));
 const seen=useCallback((id:string)=>update(s=>s.seen.includes(id)?s:{...s,seen:[...s.seen,id]}),[update]);
 const switchView=(next:View)=>{if(view==='feed')feedScroll.current=window.scrollY;setView(next);requestAnimationFrame(()=>window.scrollTo({top:next==='feed'?feedScroll.current:0,behavior:'instant'}));};
 const openReader=(post:Post,slide=0)=>{history.pushState({learnieModal:true},'',sharePath(post.id,slide,BASE));setRoute({id:post.id,slide});seen(post.id);};
 const closeReader=()=>{if(history.state?.learnieModal){history.back();}else{history.replaceState(null,'',BASE);setRoute(null);}};
 const share=async(post:Post,slide=0)=>{const url=new URL(sharePath(post.id,slide,BASE),location.origin).href;try{if(navigator.share){await navigator.share({url});}else if(navigator.clipboard){await navigator.clipboard.writeText(url);notify('Bağlantı kopyalandı. Aynı gönderiyi açar.');}else setShareFallback(url);}catch(e){if((e as Error).name!=='AbortError')setShareFallback(url);}};
 const installApp=async()=>{if(install){await install.prompt();const choice=await install.userChoice;if(choice.outcome==='accepted')setInstall(null);}else setInstallHelp(true);};
 const filtered=useMemo(()=>posts.filter(p=>(category==='Tümü'||p.category===category)&&(!query||normalize(`${p.title} ${p.subtitle} ${p.category} ${p.topic||''} ${p.slides.map(s=>s.text).join(' ')}`).includes(normalize(query)))),[posts,category,query]);
 const feedPosts=useMemo(()=>new Map(filtered.map(p=>[p.id,p])),[filtered]);
 const feedOrder=useMemo(()=>order.filter(id=>feedPosts.has(id)),[order,feedPosts]);
 const activePost=route?posts.find(p=>p.id===route.id):undefined;
 const stories=useMemo(()=>shuffle(posts).sort((a,b)=>Number(user.storySeen.includes(a.id))-Number(user.storySeen.includes(b.id))).slice(0,9),[posts]);
 const loadMore=useCallback(()=>{setOrder(current=>{let next=nextBatch(filtered,[],current,8);if(!next.length)next=shuffle(filtered).slice(0,8).map(p=>p.id);return [...current,...next];});},[filtered]);
 const selectCategory=(c:Category)=>{setCategory(c);setOrder(shuffle(posts.filter(p=>c==='Tümü'||p.category===c)).sort((a,b)=>Number(userRef.current.seen.includes(a.id))-Number(userRef.current.seen.includes(b.id))).map(p=>p.id));};
 const searchChange=(text:string)=>{setQuery(text);if(view!=='explore')switchView('explore');};
 const refresh=()=>{setOrder(shuffle(filtered).sort((a,b)=>Number(userRef.current.seen.includes(a.id))-Number(userRef.current.seen.includes(b.id))).map(p=>p.id));window.scrollTo({top:0,behavior:'smooth'});notify('Akışına yeni bir sıra verdik.');};
 const exportData=()=>{const blob=new Blob([JSON.stringify({app:'Learnie',version:1,exportedAt:new Date().toISOString(),state:user,preferences:prefs},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`learnie-yedek-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 const importData=async(file?:File)=>{if(!file)return;try{if(file.size>5_000_000)throw new Error('Yedek dosyası çok büyük.');const raw=await file.text();const s=parseBackup(raw);setUser(s);const backup=JSON.parse(raw);if(backup.preferences)setPrefs(backup.preferences);notify('Kaydettiklerin ve geçmişin geri yüklendi.');}catch(e){notify((e as Error).message);}if(importInput.current)importInput.current.value='';};
 return <div className={`app-shell ${view==='reels'?'reels-open':''}`}>
 <aside className="sidebar"><a className="brand" href={BASE} onClick={e=>{e.preventDefault();switchView('feed');}}><span className="brand-symbol">l<Sparkles size={14}/></span>learnie<span className="brand-dot">.</span></a><nav aria-label="Ana gezinme">{navigation.map(([v,label,Icon])=><button key={v} className={`nav-item ${view===v?'selected':''}`} onClick={()=>switchView(v)}><Icon size={22} strokeWidth={view===v?2.3:1.8}/><span>{label}</span>{v==='saved'&&user.saved.length>0&&<small>{user.saved.length}</small>}</button>)}</nav><div className="sidebar-bottom"><button className="install-card" onClick={installApp}><span className="install-icon"><Download size={21}/></span><span><strong>Merakın hep yanında.</strong><small>Ana ekranına ekle <ArrowUpRight size={12}/></small></span></button><button className="user-menu" onClick={()=>switchView('profile')}><span className="user-avatar">{user.name[0]}</span><span><strong>{user.name}</strong><small>Keşfetmeye devam</small></span><ChevronRight size={16}/></button><p className="sidebar-foot">Biraz merak, her gün.</p></div></aside>
 <div className="workspace"><header className="topbar"><a className="mobile-brand brand" href={BASE} onClick={e=>{e.preventDefault();switchView('feed');}}>learnie<span className="brand-dot">.</span></a><div className="topbar-greeting"><span>MERAKIN PEŞİNDEN</span><strong>{view==='feed'?'Bugün ne keşfedeceğiz?':navigation.find(n=>n[0]===view)?.[1]}</strong></div><div className="searchbox"><Search size={18}/><input aria-label="İçerik ara" value={query} placeholder="Bir şey merak et…" onChange={e=>searchChange(e.target.value)}/>{query&&<button aria-label="Aramayı temizle" onClick={()=>setQuery('')}><X size={15}/></button>}<kbd>⌕</kbd></div><IconButton label={dark?'Açık temaya geç':'Koyu temaya geç'} className="theme-toggle" onClick={()=>setPrefs({theme:dark?'light':'dark'})}>{dark?<Sun size={21}/>:<Moon size={21}/>}</IconButton><IconButton label="Uygulamayı yükle" className="mobile-install" onClick={installApp}><Download size={22}/></IconButton></header>
 {offline&&<div className="connection-note"><WifiOff size={16}/> Çevrimdışısın. Kaydedilmiş metinler açık; dış görseller ve videolar bağlantı isteyebilir.</div>}{newVersion&&<div className="connection-note">Yeni bir Learnie sürümü hazır.<button onClick={()=>{newVersion.postMessage({type:'SKIP_WAITING'});navigator.serviceWorker.addEventListener('controllerchange',()=>location.reload(),{once:true});}}>Güncelle</button></div>}
 <div className={`main-grid ${view==='reels'?'reels-layout':''}`}><main className={`main-column ${view}`}>
 {(view==='feed'||view==='explore')&&<div className="category-strip" aria-label="Konular">{categories.map(c=><button key={c} className={category===c?'selected':''} onClick={()=>selectCategory(c)}>{c==='Tümü'&&<Sparkles size={14}/>} {c}</button>)}</div>}
 {loading?<div className="loading-state"><span className="loading-mark">l</span><p>Merak edeceğin şeyler geliyor…</p></div>:error?<div className="empty-state"><WifiOff size={32}/><h2>Biraz bağlantı lazım.</h2><p>{error}</p><button className="primary-button" onClick={()=>location.reload()}>Yeniden dene</button></div>:<>
 {view==='feed'&&<><div className="section-label"><span>Bir hikâyeye dal</span><small>Bir konu, birkaç keşif</small></div><div className="stories">{stories.map((p,i)=><button className={`story-avatar ${user.storySeen.includes(p.id)?'watched':''}`} key={p.id} onClick={()=>setStory(p)}><span className="story-ring"><Cover post={p} eager={i<6}/><span className="story-indicator"><Plus size={10}/></span></span><span>{p.category}</span></button>)}</div><div className="feed-heading"><h1>Senin için<span>Her kaydırmada yeni bir şey.</span></h1><IconButton label="Akışı karıştır" onClick={refresh}><Shuffle size={19}/></IconButton></div>{!feedOrder.length?<Empty text="Bu konuda henüz bir gönderi yok."/>:<VirtualFeed ids={feedOrder} posts={feedPosts} user={user} onLoadMore={loadMore} seenAtStart={seenAtStart.current} onLike={id=>toggle('liked',id)} onSave={id=>toggle('saved',id)} onComments={setComments} onShare={share} onOpen={openReader} onStory={setStory} onSeen={seen}/>}</>}
 {view==='explore'&&<><div className="page-title"><span className="eyebrow">BİRAZ DAHA UZAĞA</span><h1>{query?'Aklındaki şeyi bul.':'Merakın nereye götürsün?'}</h1><p>{query?`${filtered.length} gönderi bulundu`:'Bir konudan diğerine. Arada hiç beklemediğin bir keşif.'}</p></div><Explore posts={filtered} onOpen={openReader}/></>}
 {view==='saved'&&<Saved onCollections={collections=>update(s=>({...s,collections}))} posts={posts} user={user} onOpen={openReader} onRemove={id=>toggle('saved',id)} onRead={toggleRead}/>}
 {view==='reels'&&<Suspense fallback={<div className="loading-state">Anlatımlar hazırlanıyor…</div>}><Reels onClose={()=>switchView('feed')} onComments={setComments} visible={!route&&!story&&!comments} posts={posts} user={user} onLike={id=>toggle('liked',id)} onSave={id=>toggle('saved',id)} onShare={share} onOpen={openReader} onSeen={seen}/></Suspense>}
 {view==='profile'&&<><div className="page-title"><span className="eyebrow">MERAKININ İZLERİ</span><h1>Merhaba, {user.name}.</h1><p>Küçük keşifler birikir.</p></div><div className="stats-grid"><div><strong>{user.seen.length}</strong><span>Gördüğün gönderi</span></div><div><strong>{user.saved.length}</strong><span>Kaydettiğin</span></div><div><strong>{Object.keys(user.answers).length}</strong><span>Yanıtladığın soru</span></div></div><ThemeSettings/><section className="settings-card preference-card"><h2>Anlatım tercihlerin</h2><FocusSettings/></section><section className="settings-card"><h2>Kendine ait bir alan.</h2><label className="field-label">Sana nasıl seslenelim?<input value={user.name} maxLength={30} onChange={e=>update(s=>({...s,name:e.target.value}))} onBlur={()=>{if(!user.name.trim())update(s=>({...s,name:'Meraklı'}));}}/></label><label className="switch-row"><span><strong>Örnek sosyal etkileşimler</strong><small>Kurgu profiller, yorumlar ve beğeni sayıları gösterilsin.</small></span><input type="checkbox" role="switch" checked={user.simulation} onChange={e=>update(s=>({...s,simulation:e.target.checked}))}/></label><button className="settings-action" onClick={installApp}><Download size={19}/><span><strong>Ana ekranına ekle</strong><small>Learnie'ye uygulama gibi ulaş.</small></span><ChevronRight size={17}/></button></section><section className="settings-card"><h2>Keşiflerini yanında taşı.</h2><p>Geçmişin, beğenilerin ve notların bu tarayıcıda saklanır. Tarayıcı verileri silinirse kaybolabilir. Başka bir cihaza geçerken yedeğini alabilirsin.</p><div className="backup-actions"><button className="secondary-button" onClick={exportData}><Download size={17}/> Yedeğini indir</button><button className="secondary-button" onClick={()=>importInput.current?.click()}><Upload size={17}/> Yedekten yükle</button></div><input type="file" ref={importInput} accept="application/json,.json" hidden onChange={e=>importData(e.target.files?.[0])}/><p className="local-note">Yedekten yükleme, bu cihazdaki mevcut keşif kayıtlarının yerini alır.</p></section><div className="about-learnie"><span className="brand">learnie<span className="brand-dot">.</span></span><p>{posts.length} kaynaklı içerik · keşif arşivi</p><p>Her yeni içerik, yeni bir pencere.</p></div></>}
 </>}
 </main>{view!=='reels'&&<aside className="right-column"><div className="daily-card"><div className="daily-top"><span className="eyebrow">BUGÜNÜN KÜÇÜK MOLASI</span><Sparkles size={19}/></div><h2>Biraz dünyadan.<br/>Biraz kendinden.</h2><p>Yeni bir şey öğrenmek için güzel bir gün.</p><div className="daily-progress"><span>{user.seen.length}<small> / {posts.length||'—'}</small></span><span>keşfedilen gönderi</span></div><div className="progress-track"><i style={{width:`${posts.length?Math.min(100,user.seen.length/posts.length*100):0}%`}}/></div></div><div className="right-heading"><h3>Merak rotaları</h3><button onClick={()=>switchView('explore')}>Tümü <ArrowUpRight size={14}/></button></div><div className="topic-list">{(['Uzay','Sanat','Felsefe','İnanç'] as Category[]).map(c=>{const Icon=categoryIcons[c];return <button key={c} onClick={()=>{selectCategory(c);switchView('explore');}}><span className={`topic-icon topic-${c}`}><Icon size={19}/></span><span><strong>{c}</strong><small>{posts.filter(p=>p.category===c).length} keşif seni bekliyor</small></span><ChevronRight size={15}/></button>;})}</div>{posts.find(p=>p.category==='Sanat')&&<button className="editor-pick" onClick={()=>openReader(posts.find(p=>p.category==='Sanat')!)}><Cover post={posts.find(p=>p.category==='Sanat')!}/><span><small>YAKINDAN BAK</small><strong>Bir eserin içinde<br/>kaybolmaya ne dersin?</strong><ArrowUpRight size={20}/></span></button>}<p className="right-footer">Kaynakları açık. Merakı sınırsız.<br/><span>Learnie © {new Date().getFullYear()}</span></p></aside>}</div>
 </div><nav className="mobile-nav" aria-label="Mobil gezinme">{navigation.map(([v,label,Icon])=><button key={v} className={view===v?'selected':''} onClick={()=>switchView(v)} aria-label={label} aria-current={view===v?'page':undefined}><Icon size={23}/><span>{v==='reels'?'Anlatımlar':v==='saved'?'Kaydedilen':v==='profile'?'Ben':label}</span></button>)}</nav>
 {comments&&<CommentsSheet post={comments} user={user} onClose={()=>setComments(null)} onAdd={text=>update(s=>({...s,comments:{...s.comments,[comments.id]:[...(s.comments[comments.id]||[]),{text,createdAt:new Date().toISOString()}]}}))}/>}
 {activePost&&<Reader key={activePost.id} post={activePost} user={user} initialSlide={route?.slide||0} onClose={closeReader} onSave={()=>toggle('saved',activePost.id)} onShare={()=>share(activePost)} onRead={()=>toggleRead(activePost.id)} onAnswer={n=>update(s=>({...s,answers:{...s.answers,[activePost.id]:n}}))} onStory={()=>setStory(activePost)}/>}
 {route&&!activePost&&!loading&&<Dialog title="Gönderi bulunamadı" onClose={closeReader}><div className="empty-state"><p>Bu bağlantıya ait bir içerik bulamadık.</p><button className="primary-button" onClick={closeReader}>Akışa dön</button></div></Dialog>}
 {story&&<Dialog title={story.title} onClose={()=>setStory(null)} full><Suspense fallback={<div className="loading-state">Hikâye hazırlanıyor…</div>}><FilmPlayer key={story.id} post={story} story saved={user.saved.includes(story.id)} onSave={()=>toggle('saved',story.id)} onShare={()=>share(story)} onClose={()=>setStory(null)} onSeen={()=>{seen(story.id);update(s=>({...s,storySeen:[...new Set([...s.storySeen,story.id])]}));}} onEnd={()=>{if(activePost){setStory(null);return;}const next=stories[(stories.findIndex(p=>p.id===story.id)+1)%stories.length];setStory(next);}}/></Suspense></Dialog>}
 {installHelp&&<Dialog title="Learnie hep yanında." onClose={()=>setInstallHelp(false)}><div className="install-help"><span className="app-icon-preview">l<Sparkles size={22}/></span><h2>Ana ekranına ekle.</h2><p><strong>iPhone / iPad:</strong> Safari’de paylaş düğmesine dokun, ardından “Ana Ekrana Ekle”yi seç.</p><p><strong>Android:</strong> Chrome menüsünden “Uygulamayı yükle” veya “Ana ekrana ekle”yi seç.</p><p><strong>Bilgisayar:</strong> Destekleyen tarayıcılarda adres çubuğundaki yükleme simgesini kullan.</p><p className="local-note">Yükleme seçeneği görünmüyorsa siteyi kendi tarayıcında aç. Metinler ilk ziyaretten sonra çevrimdışı açılabilir; dış görseller ve videolar internet ister.</p></div></Dialog>}
 {shareFallback&&<Dialog title="Bu keşfi paylaş" onClose={()=>setShareFallback('')}><div className="share-fallback"><p>Bağlantıyı kopyalayıp gönderebilirsin.</p><input aria-label="Paylaşım bağlantısı" readOnly value={shareFallback} onFocus={e=>e.target.select()}/></div></Dialog>}
 {toast&&<div className="toast" role="status"><Check size={17}/>{toast}</div>}
 </div>;
}
function Empty({text}:{text:string}){return <div className="empty-state"><Search size={30}/><p>{text}</p></div>;}
function VirtualFeed({ids,posts,user,onLoadMore,seenAtStart,onLike,onSave,onComments,onShare,onOpen,onStory,onSeen}:{ids:string[];posts:Map<string,Post>;user:UserState;onLoadMore:()=>void;seenAtStart:Set<string>;onLike:(id:string)=>void;onSave:(id:string)=>void;onComments:(p:Post)=>void;onShare:(p:Post,s:number)=>void;onOpen:(p:Post,s:number)=>void;onStory:(p:Post)=>void;onSeen:(id:string)=>void}){
 const listRef=useRef<HTMLDivElement>(null);const [margin,setMargin]=useState(0);useLayoutEffect(()=>{const measure=()=>setMargin((listRef.current?.getBoundingClientRect().top||0)+window.scrollY);measure();window.addEventListener('resize',measure);return()=>window.removeEventListener('resize',measure);},[]);
 const virtual=useWindowVirtualizer({count:ids.length,estimateSize:()=>710,overscan:2,scrollMargin:margin,getItemKey:i=>`${ids[i]}-${i}`});const rows=virtual.getVirtualItems();
 useEffect(()=>{const last=rows.at(-1);if(last&&last.index>=ids.length-2&&ids.length)onLoadMore();},[rows.at(-1)?.index,ids.length,onLoadMore]);
 return <div ref={listRef} className="virtual-feed" style={{height:virtual.getTotalSize(),position:'relative'}}>{rows.map(row=>{const p=posts.get(ids[row.index]);return p?<div key={row.key} data-index={row.index} ref={virtual.measureElement} style={{position:'absolute',top:0,left:0,width:'100%',transform:`translateY(${row.start-margin}px)`,paddingBottom:26}}><PostCard post={p} user={user} eager={row.index===0} onLike={()=>onLike(p.id)} onSave={()=>onSave(p.id)} onComments={()=>onComments(p)} onShare={s=>onShare(p,s)} onOpen={s=>onOpen(p,s)} onStory={()=>onStory(p)} onSeen={()=>onSeen(p.id)} revisited={seenAtStart.has(p.id)||ids.indexOf(p.id)<row.index}/></div>:null;})}</div>;
}
