import {PostThumbnail} from './PostDesign';
import {useState} from 'react';
import {Bookmark,Check,Folder,Plus} from 'lucide-react';
import {Dialog,Cover} from './components';
import {normalize} from './engine.mjs';
import {setCollectionMembership} from './collections.mjs';
import type {Post,UserState,Collection} from './types';
export default function CollectionPicker({post,user,posts,onCollections,onRemove,onClose}:{post:Post;user:UserState;posts:Post[];onCollections:(c:Collection[])=>void;onRemove:()=>void;onClose:()=>void}){
 const [creating,setCreating]=useState(false),[name,setName]=useState(''),[error,setError]=useState('');
 const create=()=>{const value=name.trim();if(!value)return;if(user.collections.some(c=>normalize(c.name)===normalize(value))){setError('Bu isimde bir koleksiyonun var. Listeden seçebilirsin.');return;}onCollections([...user.collections,{id:crypto.randomUUID(),name:value,postIds:[post.id],createdAt:new Date().toISOString()}]);setCreating(false);setName('');setError('');};
 return <Dialog title="Koleksiyona kaydet" onClose={onClose}><div className="save-picker"><div className="save-confirmation"><span className="save-thumb"><PostThumbnail post={post}/></span><span><strong>Kaydedildi</strong><small>Tüm gönderiler</small></span><Bookmark fill="currentColor" size={22}/></div><p>İstersen bir koleksiyona da ekle.</p><div className="save-collections">{user.collections.map(c=>{const cover=posts.find(p=>c.postIds.includes(p.id));return <label className="save-collection" key={c.id}><span className="save-folder">{cover?<span className="save-thumb"><PostThumbnail post={cover}/></span>:<Folder size={23}/>}</span><span><strong>{c.name}</strong><small>{c.postIds.length} gönderi</small></span><input type="checkbox" aria-label={`${c.name} koleksiyonuna ekle`} checked={c.postIds.includes(post.id)} onChange={e=>onCollections(setCollectionMembership(user.collections,c.id,post.id,e.target.checked))}/></label>;})}</div>{creating?<form className="save-create" onSubmit={e=>{e.preventDefault();create();}}><label>Yeni koleksiyon<input autoFocus aria-label="Yeni koleksiyon adı" value={name} maxLength={50} placeholder="Bir isim ver…" onChange={e=>{setName(e.target.value);setError('');}}/></label>{error&&<p role="alert">{error}</p>}<div><button type="button" onClick={()=>setCreating(false)}>Vazgeç</button><button className="primary-button" disabled={!name.trim()} type="submit">Oluştur ve ekle</button></div></form>:<button className="save-new" onClick={()=>setCreating(true)}><Plus size={23}/> Yeni koleksiyon</button>}<button className="primary-button save-done" onClick={onClose}><Check size={17}/> Bitti</button><button className="save-remove" onClick={onRemove}>Kaydedilenlerden kaldır</button></div></Dialog>;
}
