import {useEffect,useRef,useState,type ReactNode,type CSSProperties} from 'react';
import {motion,AnimatePresence,useReducedMotion} from 'motion/react';
import {Swiper,SwiperSlide} from 'swiper/react';
import {Keyboard,A11y} from 'swiper/modules';
import {ArrowUpRight,Bookmark,Check,ChevronLeft,ChevronRight,Heart,ImageOff,MessageCircle,MoreHorizontal,Play,Send,Share2,Sparkles,X,BookOpen,Info} from 'lucide-react';
import type {Post,UserState} from './types';
import {seedNumber} from './engine.mjs';
import 'swiper/css';
export function IconButton({label,children,onClick,active=false,className=''}:{label:string;children:ReactNode;onClick?:()=>void;active?:boolean;className?:string}) {return <button type="button" aria-label={label} title={label} aria-pressed={active} className={`icon-button ${active?'active':''} ${className}`} onClick={onClick}>{children}</button>;}
export function Cover({post,className='',eager=false}:{post:Post;className?:string;eager?:boolean}){const [failed,setFailed]=useState(false);return failed?<div className={`image-fallback ${className}`}><ImageOff size={26}/><span>Görsel şu an yüklenemedi</span><button onClick={()=>setFailed(false)}>Yeniden dene</button></div>:<img className={className} src={post.cover.url} alt={post.cover.alt} loading={eager?'eager':'lazy'} decoding="async" referrerPolicy="no-referrer" style={{objectPosition:post.cover.position||'center'}} onError={()=>setFailed(true)}/>;}
export function Avatar({post,size=''}:{post:Post;size?:string}){return <span className={`avatar ${size}`} style={{background:post.accent}} aria-hidden="true">{post.account.split(' ').map(x=>x[0]).slice(0,2).join('')}</span>;}
export function Dialog({title,children,onClose,wide=false,full=false}:{title:string;children:ReactNode;onClose:()=>void;wide?:boolean;full?:boolean}){
 const ref=useRef<HTMLDialogElement>(null);const closeRef=useRef(onClose);closeRef.current=onClose;
 useEffect(()=>{const el=ref.current!;const before=document.activeElement as HTMLElement;el.showModal();const overflow=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{el.close();document.body.style.overflow=overflow;before?.focus();};},[]);
 return <dialog ref={ref} className={`dialog ${wide?'wide':''} ${full?'full':''}`} onCancel={e=>{e.preventDefault();closeRef.current();}} onClick={e=>{if(e.target===ref.current)closeRef.current();}}><div className="dialog-inner"><header className="dialog-head"><h2>{title}</h2><IconButton label="Kapat" onClick={onClose}><X/></IconButton></header>{children}</div></dialog>;
}
export function Sources({post}:{post:Post}){return <div className="sources"><span className="eyebrow">DAHA YAKINDAN</span><h3>Bilginin izini sür.</h3>{post.sources.map(s=><a key={s.url} href={s.url} target="_blank" rel="noreferrer">{s.label}<ArrowUpRight size={18}/></a>)}<p>Görsel: <a href={post.cover.source} target="_blank" rel="noreferrer">{post.cover.credit}</a> · {post.cover.licenseUrl?<a href={post.cover.licenseUrl} target="_blank" rel="noreferrer">{post.cover.license}</a>:post.cover.license} · Kadraj ekrana uyarlanmıştır.</p><p>Kontrol: {new Date(post.updatedAt).toLocaleDateString('tr-TR')}</p></div>;}
export function Experiment({kind}:{kind:'pressure'|'light'}){const [value,setValue]=useState(kind==='pressure'?20:450);return <div className={`experiment ${kind}`}><span className="eyebrow">KÜÇÜK BİR DENEY</span><h3>{kind==='pressure'?'Derine indikçe ne değişir?':'Işığın rengini değiştir.'}</h3>{kind==='pressure'?<div className="pressure-display"><span>{value}<small>metre</small></span><span className="pressure-arrow">→</span><span>{(1+value/10).toFixed(1)}<small>yaklaşık atmosfer</small></span></div>:<div className="light-sample" style={{background:`hsl(${270-(value-380)/400*270},85%,55%)`}}><span>{value} nm</span></div>}<input aria-label={kind==='pressure'?'Derinlik':'Dalga boyu'} type="range" min={kind==='pressure'?0:380} max={kind==='pressure'?100:780} step={kind==='pressure'?5:10} value={value} onChange={e=>setValue(Number(e.target.value))}/><div className="range-labels"><span>{kind==='pressure'?'Yüzey':'Kısa dalga'}</span><span>{kind==='pressure'?'100 m':'Uzun dalga'}</span></div><p>{kind==='pressure'?'Suyun uyguladığı basınç her 10 metrede yaklaşık 1 atmosfer artar. Burada yüzeydeki hava basıncı da toplama dahil.':'Dalga boyu ışığın rengini etkiler. Kısa dalga boylu görünür ışık, atmosfer moleküllerince daha güçlü saçılır. Renk şeridi yaklaşık bir gösterimdir.'}</p></div>;}
export function Quiz({post,answer,onAnswer}:{post:Post;answer?:number;onAnswer:(n:number)=>void}){const q=post.quiz;if(!q)return null;return <section className="quiz"><span className="eyebrow">BİR TAHMİNİN VAR MI?</span><h3>{q.question}</h3><div className="quiz-options">{q.options.map((o,i)=><button key={o} disabled={answer!==undefined} className={answer!==undefined?(i===q.answer?'correct':i===answer?'incorrect':''):''} onClick={()=>onAnswer(i)}>{o}{answer!==undefined&&i===q.answer&&<Check size={17}/>}</button>)}</div>{answer!==undefined&&<p className="answer-explanation" role="status">{q.explanation}</p>}</section>;}
interface CardProps {post:Post;user:UserState;onLike:()=>void;onSave:()=>void;onComments:()=>void;onShare:(slide:number)=>void;onOpen:(slide:number)=>void;onStory:()=>void;onSeen:()=>void;revisited?:boolean;eager?:boolean;}
export function PostCard({post,user,onLike,onSave,onComments,onShare,onOpen,onStory,onSeen,revisited,eager}:CardProps){
 const [slide,setSlide]=useState(0);const [burst,setBurst]=useState(false);const [sources,setSources]=useState(false);const [expanded,setExpanded]=useState(false);const reduced=useReducedMotion();const cardRef=useRef<HTMLElement>(null);const seenRef=useRef(onSeen);seenRef.current=onSeen;
 useEffect(()=>{let timer:ReturnType<typeof setTimeout>;const observer=new IntersectionObserver(([entry])=>{clearTimeout(timer);if(entry.isIntersecting)timer=setTimeout(()=>seenRef.current(),1400);},{threshold:.35});if(cardRef.current)observer.observe(cardRef.current);return()=>{clearTimeout(timer);observer.disconnect();};},[post.id]);
 const liked=user.liked.includes(post.id);const saved=user.saved.includes(post.id);const count=120+seedNumber(post.id)%2900+(liked?1:0);
 const doubleLike=()=>{if(!liked)onLike();setBurst(true);setTimeout(()=>setBurst(false),650);};
 return <article className="post" ref={cardRef} style={{'--post-accent':post.accent} as CSSProperties}>
 <header className="post-header"><button className="account-button" onClick={onStory}><Avatar post={post}/><span><strong>{post.account}</strong><small>{post.category} <span>·</span> {post.minutes} dk</small></span></button><IconButton label="Kaynaklar ve görsel bilgisi" onClick={()=>setSources(true)}><MoreHorizontal size={22}/></IconButton></header>
 <div className="post-visual" onDoubleClick={doubleLike}>
 <Swiper modules={[Keyboard,A11y]} keyboard={{enabled:true,onlyInViewport:true}} onSlideChange={s=>setSlide(s.activeIndex)} nested touchAngle={35} resistanceRatio={.65}>
 <SwiperSlide><div className="cover-slide"><Cover post={post} eager={eager}/><div className="cover-shade"/><div className="media-top"><span className="glass-tag">{post.format==='experiment'?'Dene & keşfet':post.format==='reel'?'Kısa anlatım':post.category}</span><span className="slide-count">1 / {post.slides.length+1}</span></div><div className="cover-copy"><span className="eyebrow">{post.category.toLocaleUpperCase('tr-TR')}</span><h2>{post.title}</h2><button className="cover-cta" onClick={()=>onOpen(0)}>Biraz daha yakından <ArrowUpRight size={17}/></button></div>{(post.format==='reel'||post.format==='story')&&<button className="play-cover" aria-label={`${post.title} anlatımını oynat`} onClick={onStory}><Play fill="currentColor" size={23}/></button>}</div></SwiperSlide>
 {post.slides.map((s,i)=><SwiperSlide key={i}><div className={`text-slide slide-${i%3}`}><div className="text-slide-top"><span className="eyebrow">{s.kicker||post.category}</span><span>{i+2} / {post.slides.length+1}</span></div><span className="slide-number">0{i+1}</span><h3>{s.title}</h3><p>{s.text}</p><div className="slide-foot"><span>Learnie</span><span>Kaydırmaya devam <ChevronRight size={15}/></span></div></div></SwiperSlide>)}
 </Swiper>
 <AnimatePresence>{burst&&<motion.div className="heart-burst" initial={{opacity:0,scale:.3}} animate={{opacity:1,scale:1.1}} exit={{opacity:0,scale:1.4}} transition={{duration:reduced?0:.2}}><Heart fill="white" stroke="white" size={92}/></motion.div>}</AnimatePresence>
 </div>
 <div className="post-actions"><div><IconButton label={liked?'Beğeniyi kaldır':'Beğen'} active={liked} className="like" onClick={onLike}><Heart fill={liked?'currentColor':'none'}/></IconButton><IconButton label="Yorumları aç" onClick={onComments}><MessageCircle/></IconButton><IconButton label="Gönderiyi paylaş" onClick={()=>onShare(slide)}><Send/></IconButton></div><div className="pagination-dots" aria-label={`${slide+1}. kart`}>{Array.from({length:post.slides.length+1},(_,i)=><span className={i===slide?'selected':''} key={i}/>)}</div><IconButton label={saved?'Kaydı kaldır':'Kaydet'} active={saved} onClick={onSave}><Bookmark fill={saved?'currentColor':'none'}/></IconButton></div>
 <div className="post-caption">{user.simulation&&<div className="social-count"><Heart size={13} fill="currentColor"/><strong>{count.toLocaleString('tr-TR')}</strong><span>örnek beğeni</span></div>}<p><strong>{post.handle}</strong> {post.subtitle}</p>{expanded&&<p className="expanded-copy">{post.slides[0].text}</p>}<div className="caption-bottom"><button onClick={()=>setExpanded(!expanded)}>{expanded?'Daha az göster':'Devamını oku'}</button><button onClick={()=>onOpen(slide)}><BookOpen size={14}/> İncele</button></div>{revisited&&<span className="revisited">Yeniden keşif</span>}</div>
 {sources&&<Dialog title="Kaynaklar" onClose={()=>setSources(false)}><Sources post={post}/></Dialog>}
 </article>;
}
export function Comments({post,user,onAdd,onClose}:{post:Post;user:UserState;onAdd:(t:string)=>void;onClose:()=>void}){const [text,setText]=useState('');return <Dialog title="Sohbete bir düşünce bırak" onClose={onClose}><div className="comment-list">{user.simulation&&<><p className="simulation-note"><Info size={15}/> Aşağıdaki profiller ve yorumlar canlandırmadır.</p>{post.comments.map((c,i)=><div className="comment" key={i}><span className="comment-avatar" style={{background:['#efe8d8','#e3eee7','#e9e5ef'][i%3]}}>{c.name[0]}</span><div><strong>{c.name}<small>Örnek yorum</small></strong><p>{c.text}</p></div></div>)}</>}{(user.comments[post.id]||[]).map((c,i)=><div className="comment" key={`local-${i}`}><span className="comment-avatar mine">{user.name[0]}</span><div><strong>{user.name}<small>Bu cihazda</small></strong><p>{c.text}</p></div></div>)}{!user.simulation&&!user.comments[post.id]?.length&&<p>Henüz bir not bırakmadın.</p>}</div><form className="comment-form" onSubmit={e=>{e.preventDefault();if(text.trim()){onAdd(text.trim());setText('');}}}><label className="sr-only" htmlFor="comment-input">Düşüncen</label><input id="comment-input" value={text} maxLength={1000} onChange={e=>setText(e.target.value)} placeholder="Aklından ne geçti?"/><button className="round-primary" disabled={!text.trim()} aria-label="Yorumu kaydet"><Send size={19}/></button></form><p className="local-note">Yazdıkların yalnızca bu cihazda saklanır.</p></Dialog>;}
export function Reader({post,user,initialSlide,onClose,onAnswer,onStory,onSave,onShare,onRead}:{post:Post;user:UserState;initialSlide:number;onClose:()=>void;onSave:()=>void;onShare:()=>void;onRead:()=>void;onAnswer:(n:number)=>void;onStory:()=>void}){
 const ref=useRef<HTMLDivElement>(null);useEffect(()=>{if(initialSlide>0)ref.current?.querySelector(`[data-slide="${initialSlide}"]`)?.scrollIntoView({block:'start'});},[]);
 return <Dialog title={post.account} onClose={onClose} wide><div className="reader" ref={ref}><div className="reader-toolbar"><button className="reader-watch" onClick={onStory}><Play size={17}/> İzle</button><button onClick={onRead} aria-pressed={user.read.includes(post.id)}>{user.read.includes(post.id)?<Check size={17}/>:<BookOpen size={17}/>} {user.read.includes(post.id)?'Okundu':'Okudum'}</button><span/><IconButton label="Gönderiyi paylaş" onClick={onShare}><Send size={19}/></IconButton><IconButton label={user.saved.includes(post.id)?'Kaydı kaldır':'Daha sonra okumak için kaydet'} active={user.saved.includes(post.id)} onClick={onSave}><Bookmark fill={user.saved.includes(post.id)?'currentColor':'none'}/></IconButton></div><div className="reader-cover"><Cover post={post} eager/><span className="glass-tag">{post.category} · {post.minutes} dk</span></div><div className="reader-body"><h1>{post.title}</h1><p className="reader-lead">{post.subtitle}</p>{post.slides.map((s,i)=><section key={i} data-slide={i+1}><span className="eyebrow">0{i+1} / {s.kicker||post.category}</span><h2>{s.title}</h2><p>{s.text}</p></section>)}{post.experiment&&<Experiment kind={post.experiment}/>}<Quiz post={post} answer={user.answers[post.id]} onAnswer={onAnswer}/><button className="primary-button" onClick={onStory}><Play size={17}/> Kısa anlatımı izle</button>{post.video&&<div className="video-block"><h3>{post.video.title}</h3><p>{post.video.language}</p>{post.video.kind==='youtube'?<iframe src={`https://www.youtube-nocookie.com/embed/${post.video.url}`} title={post.video.title} loading="lazy" allow="accelerometer; encrypted-media; gyroscope; picture-in-picture" allowFullScreen/>:<video controls playsInline preload="none" src={post.video.url}/>}<a href={post.video.kind==='youtube'?`https://www.youtube.com/watch?v=${post.video.url}`:post.video.url} target="_blank" rel="noreferrer">Video açılmazsa kaynağında izle <ArrowUpRight size={14}/></a></div>}<Sources post={post}/></div></div></Dialog>;
}
