import {EditorialCover,EditorialSlide,PostNarrative} from './PostDesign';
import VideoEmbed from './VideoEmbed';
import {engagement,formatCount} from './social.mjs';
import DiscoveryLab from './DiscoveryLab';
import {useEffect,useRef,useState,type ReactNode,type CSSProperties} from 'react';
import {motion,AnimatePresence,useReducedMotion} from 'motion/react';
import {Swiper,SwiperSlide} from 'swiper/react';
import {Keyboard,A11y} from 'swiper/modules';
import {ArrowUpRight,Bookmark,Check,ChevronLeft,ChevronRight,Heart,ImageOff,MessageCircle,MoreHorizontal,Play,Send,Share2,Sparkles,X,BookOpen,Info} from 'lucide-react';
import type {Post,UserState} from './types';
import {seedNumber} from './engine.mjs';
import 'swiper/css';
export function IconButton({label,children,onClick,active=false,className=''}:{label:string;children:ReactNode;onClick?:()=>void;active?:boolean;className?:string}) {return <button type="button" aria-label={label} title={label} aria-pressed={active} className={`icon-button ${active?'active':''} ${className}`} onClick={onClick}>{children}</button>;}
export function Cover({post,className='',eager=false}:{post:Post;className?:string;eager?:boolean}){const [failed,setFailed]=useState(false);return failed?<div className={`image-fallback ${className}`}><ImageOff size={26}/><span>Görsel şu an yüklenemedi</span><button onClick={()=>setFailed(false)}>Yeniden dene</button></div>:<img className={className} src={post.cover.url} alt={post.cover.alt} loading={eager?'eager':'lazy'} decoding="async" referrerPolicy="no-referrer" style={{objectPosition:post.cover.position||'center'}} onError={()=>setFailed(true)}/>;}
export function Avatar({post,size=''}:{post:Post;size?:string}){const [failed,setFailed]=useState(false);return <span className={`avatar ${size}`} aria-hidden="true">{!failed?<img src={post.avatar||post.cover.url} alt="" loading="lazy" referrerPolicy="no-referrer" onError={()=>setFailed(true)}/>:<Sparkles size={20}/>}</span>;}
export function SocialActions({post,user,onLike,onComments,onShare}:{post:Post;user:UserState;onLike:()=>void;onComments:()=>void;onShare:()=>void}){const counts=engagement(post,user),liked=user.liked.includes(post.id);return <div className="social-actions"><button aria-label={liked?'Beğeniyi kaldır':'Beğen'} aria-pressed={liked} className={liked?'is-liked':''} onClick={onLike}><Heart fill={liked?'currentColor':'none'}/>{counts.likes>0&&<span>{formatCount(counts.likes)}</span>}</button><button aria-label="Yorumları aç" onClick={onComments}><MessageCircle/>{counts.comments>0&&<span>{formatCount(counts.comments)}</span>}</button><button aria-label="Gönderiyi paylaş" onClick={onShare}><Send/>{counts.shares>0&&<span>{formatCount(counts.shares)}</span>}</button></div>;}
export function Dialog({title,children,onClose,wide=false,full=false}:{title:string;children:ReactNode;onClose:()=>void;wide?:boolean;full?:boolean}){
 const ref=useRef<HTMLDialogElement>(null);const closeRef=useRef(onClose);closeRef.current=onClose;
 useEffect(()=>{const el=ref.current!;const before=document.activeElement as HTMLElement;el.showModal();const overflow=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{el.close();document.body.style.overflow=overflow;before?.focus();};},[]);
 return <dialog ref={ref} aria-label={title} className={`dialog ${wide?'wide':''} ${full?'full':''}`} onCancel={e=>{e.preventDefault();closeRef.current();}} onClick={e=>{if(e.target===ref.current)closeRef.current();}}><div className="dialog-inner"><header className="dialog-head"><h2>{title}</h2><IconButton label="Kapat" onClick={onClose}><X/></IconButton></header>{children}</div></dialog>;
}
export function Sources({post}:{post:Post}){return <div className="sources"><span className="eyebrow">DAHA YAKINDAN</span><h3>Bilginin izini sür.</h3>{post.sources.map(s=><a key={s.url} href={s.url} target="_blank" rel="noreferrer">{s.label}<ArrowUpRight size={18}/></a>)}<p>Görsel: <a href={post.cover.source} target="_blank" rel="noreferrer">{post.cover.credit}</a> · {post.cover.licenseUrl?<a href={post.cover.licenseUrl} target="_blank" rel="noreferrer">{post.cover.license}</a>:post.cover.license} · Kadraj ekrana uyarlanmıştır.</p>{post.avatarCredit&&<p>Hesap görseli: <a href={post.avatarCredit.url} target="_blank" rel="noreferrer">{post.avatarCredit.label}</a></p>}<p>Kontrol: {new Date(`${post.updatedAt}T12:00:00`).toLocaleDateString('tr-TR')}</p></div>;}
export function Experiment({kind}:{kind:'pressure'|'light'}){const [value,setValue]=useState(kind==='pressure'?20:450);return <div className={`experiment ${kind}`}><span className="eyebrow">KÜÇÜK BİR DENEY</span><h3>{kind==='pressure'?'Derine indikçe ne değişir?':'Işığın rengini değiştir.'}</h3>{kind==='pressure'?<div className="pressure-display"><span>{value}<small>metre</small></span><span className="pressure-arrow">→</span><span>{(1+value/10).toFixed(1)}<small>yaklaşık atmosfer</small></span></div>:<div className="light-sample" style={{background:`hsl(${270-(value-380)/400*270},85%,55%)`}}><span>{value} nm</span></div>}<input aria-label={kind==='pressure'?'Derinlik':'Dalga boyu'} type="range" min={kind==='pressure'?0:380} max={kind==='pressure'?100:780} step={kind==='pressure'?5:10} value={value} onChange={e=>setValue(Number(e.target.value))}/><div className="range-labels"><span>{kind==='pressure'?'Yüzey':'Kısa dalga'}</span><span>{kind==='pressure'?'100 m':'Uzun dalga'}</span></div><p>{kind==='pressure'?'Suyun uyguladığı basınç her 10 metrede yaklaşık 1 atmosfer artar. Burada yüzeydeki hava basıncı da toplama dahil.':'Dalga boyu ışığın rengini etkiler. Kısa dalga boylu görünür ışık, atmosfer moleküllerince daha güçlü saçılır. Renk şeridi yaklaşık bir gösterimdir.'}</p></div>;}
export function Quiz({post,answer,onAnswer}:{post:Post;answer?:number;onAnswer:(n:number)=>void}){const q=post.quiz;if(!q)return null;return <section className="quiz"><span className="eyebrow">BİR TAHMİNİN VAR MI?</span><h3>{q.question}</h3><div className="quiz-options">{q.options.map((o,i)=><button key={o} disabled={answer!==undefined} className={answer!==undefined?(i===q.answer?'correct':i===answer?'incorrect':''):''} onClick={()=>onAnswer(i)}>{o}{answer!==undefined&&i===q.answer&&<Check size={17}/>}</button>)}</div>{answer!==undefined&&<p className="answer-explanation" role="status">{q.explanation}</p>}</section>;}
interface CardProps {post:Post;user:UserState;onLike:()=>void;onSave:()=>void;onComments:()=>void;onShare:(slide:number)=>void;onOpen:(slide:number)=>void;onStory:()=>void;onAccount:()=>void;onSeen:()=>void;revisited?:boolean;eager?:boolean;}
export function PostCard({post,user,onLike,onSave,onComments,onShare,onOpen,onStory,onAccount,onSeen,revisited,eager}:CardProps){
 const [slide,setSlide]=useState(0);const [burst,setBurst]=useState(false);const [sources,setSources]=useState(false);const [expanded,setExpanded]=useState(false);const reduced=useReducedMotion();const cardRef=useRef<HTMLElement>(null);const seenRef=useRef(onSeen);seenRef.current=onSeen;
 useEffect(()=>{let timer:ReturnType<typeof setTimeout>;const observer=new IntersectionObserver(([entry])=>{clearTimeout(timer);if(entry.isIntersecting)timer=setTimeout(()=>seenRef.current(),1400);},{threshold:.35});if(cardRef.current)observer.observe(cardRef.current);return()=>{clearTimeout(timer);observer.disconnect();};},[post.id]);
 const liked=user.liked.includes(post.id);const saved=user.saved.includes(post.id);const count=(seedNumber(post.id)%5===0?seedNumber(post.id)%80:seedNumber(post.id)%12400)+(liked?1:0);
 const doubleLike=()=>{if(!liked)onLike();setBurst(true);setTimeout(()=>setBurst(false),650);};
 return <article className="post" ref={cardRef} style={{'--post-accent':post.accent} as CSSProperties}>
 <header className="post-header"><button className="account-button" aria-label={`${post.account} profilini aç`} onClick={onAccount}><Avatar post={post}/><span><strong>{post.account}</strong><small>{post.category} <span>·</span> {post.minutes} dk</small></span></button><IconButton label="Kaynaklar ve görsel bilgisi" onClick={()=>setSources(true)}><MoreHorizontal size={22}/></IconButton></header>
 <div className="post-visual" onDoubleClick={doubleLike}>
 {post.display==='video'&&post.video?<VideoEmbed post={post}/>:post.display==='single'?<EditorialCover post={post} onOpen={()=>onOpen(0)}><Cover post={post} eager={eager}/></EditorialCover>:<Swiper modules={[Keyboard,A11y]} keyboard={{enabled:true,onlyInViewport:true}} onSlideChange={s=>setSlide(s.activeIndex)} nested touchAngle={35} resistanceRatio={.65}>
 <SwiperSlide><EditorialCover post={post} onOpen={()=>onOpen(0)}><Cover post={post} eager={eager}/></EditorialCover></SwiperSlide>
 {post.slides.map((s,i)=><SwiperSlide key={i}><EditorialSlide post={post} slide={s} index={i}/></SwiperSlide>)}
 </Swiper>}
 <AnimatePresence>{burst&&<motion.div className="heart-burst" initial={{opacity:0,scale:.3}} animate={{opacity:1,scale:1.1}} exit={{opacity:0,scale:1.4}} transition={{duration:reduced?0:.2}}><Heart fill="white" stroke="white" size={92}/></motion.div>}</AnimatePresence>
 </div>
 <div className="post-actions"><SocialActions post={post} user={user} onLike={onLike} onComments={onComments} onShare={()=>onShare(slide)}/><IconButton label={saved?'Koleksiyonları düzenle':'Kaydet'} active={saved} onClick={onSave}><Bookmark fill={saved?'currentColor':'none'}/></IconButton></div>
 {post.display!=='single'&&post.display!=='video'&&<div className="post-page-dots" aria-label={`${slide+1}. kart`}>{Array.from({length:post.slides.length+1},(_,i)=><span className={i===slide?'selected':''} key={i}/>)}</div>}
 <div className="post-caption"><p><button onClick={onAccount} aria-label={`${post.account} profilini aç`}>{post.handle}</button> {post.subtitle}</p>{expanded&&<div className="expanded-copy">{post.slides.filter(s=>s.text!==post.subtitle).map((s,i)=><p key={i}>{s.text}</p>)}</div>}<div className="caption-bottom">{post.slides.some(s=>s.text!==post.subtitle)&&<button onClick={()=>setExpanded(!expanded)}>{expanded?'Daha az göster':'devamı'}</button>}<button onClick={()=>onOpen(slide)}>Gönderiyi aç <ArrowUpRight size={14}/></button></div></div>
 {sources&&<Dialog title="Kaynaklar" onClose={()=>setSources(false)}><Sources post={post}/></Dialog>}
 </article>;
}
export function Reader({post,user,initialSlide,onClose,onAnswer,onStory,onSave,onShare,onRead,onAccount}:{post:Post;user:UserState;initialSlide:number;onClose:()=>void;onSave:()=>void;onShare:()=>void;onRead:()=>void;onAnswer:(n:number)=>void;onStory:()=>void;onAccount:()=>void}){
 const ref=useRef<HTMLDivElement>(null);useEffect(()=>{if(initialSlide>0)requestAnimationFrame(()=>ref.current?.querySelector(`[data-slide="${initialSlide}"]`)?.scrollIntoView({block:'start'}));},[initialSlide]);
 return <Dialog title={post.account} onClose={onClose} wide><div className="reader" ref={ref}><button className="reader-account" onClick={onAccount} aria-label={`${post.account} profilini aç`}><Avatar post={post}/><strong>{post.account}</strong></button><div className="reader-toolbar">{post.display!=='video'&&<button className="reader-watch" onClick={onStory}><Play size={17}/> İzle</button>}<button onClick={onRead} aria-pressed={user.read.includes(post.id)}>{user.read.includes(post.id)?<Check size={17}/>:<BookOpen size={17}/>} {user.read.includes(post.id)?'Okundu':'Okudum'}</button><span/><IconButton label="Gönderiyi paylaş" onClick={onShare}><Send size={19}/></IconButton><IconButton label={user.saved.includes(post.id)?'Koleksiyonları düzenle':'Daha sonra okumak için kaydet'} active={user.saved.includes(post.id)} onClick={onSave}><Bookmark fill={user.saved.includes(post.id)?'currentColor':'none'}/></IconButton></div><div className="reader-cover">{post.display==='video'?<VideoEmbed post={post}/>:<EditorialCover post={post} onOpen={onStory}><Cover post={post} eager/></EditorialCover>}</div><div className="reader-body"><h1>{post.title}</h1><p className="reader-lead">{post.subtitle}</p>{(post.display!=='video'||post.slides.some(s=>s.text!==post.subtitle))&&<PostNarrative post={post} initialSlide={initialSlide}/>}{post.art?.kind==='diagram'&&<DiscoveryLab post={post}/>}{post.experiment&&<Experiment kind={post.experiment}/>}<Quiz post={post} answer={user.answers[post.id]} onAnswer={onAnswer}/>{post.display!=='video'&&<button className="primary-button" onClick={onStory}><Play size={17}/> Kısa anlatımı izle</button>}{post.video&&post.display!=='video'&&<VideoEmbed post={post}/>}<Sources post={post}/></div></div></Dialog>;
}

export function VideoStory({post,active,onClose,onSave,onShare,onAccount}:{post:Post;active:boolean;onClose:()=>void;onSave:()=>void;onShare:()=>void;onAccount:()=>void}){return <div className="video-story"><header><button className="film-account" onClick={onAccount} aria-label={`${post.account} profilini aç`}><Avatar post={post}/><strong>{post.account}</strong></button><IconButton label="Videoyu kapat" onClick={onClose}><X/></IconButton></header><VideoEmbed post={post} active={active}/><div className="video-story-copy"><h2>{post.title}</h2><p>{post.subtitle}</p></div><footer><IconButton label="Video koleksiyonlarını seç" onClick={onSave}><Bookmark/></IconButton><IconButton label="Videoyu paylaş" onClick={onShare}><Send/></IconButton></footer></div>;}
