import {useEffect,useMemo,useRef,useState} from 'react';
import {AbsoluteFill,Img,interpolate,useCurrentFrame,useVideoConfig} from 'remotion';
import {Player,type PlayerRef} from '@remotion/player';
import {Swiper,SwiperSlide} from 'swiper/react';
import {Virtual,Mousewheel,Keyboard,A11y} from 'swiper/modules';
import {Bookmark,ChevronDown,ChevronLeft,ChevronRight,Heart,Pause,Play,Send,X,BookOpen,Focus,Volume2,VolumeX,Music2,MessageCircle} from 'lucide-react';
import {Avatar,IconButton} from './components';
import {FocusSettings,usePreferences,type Preferences} from './Preferences';
import {createScenes,revealUnits,visibleUnitCount} from './preferences.mjs';
import {MotionScene} from './MotionScene';
import {AmbientSound} from './audio';
import {shuffle} from './engine.mjs';
import type {Post,UserState} from './types';
let speechOwner:symbol|undefined;
function KnowledgeFilm({post,prefs,dark,reduced=false,immersive=false}:{post:Post;prefs:Preferences;dark:boolean;reduced?:boolean;immersive?:boolean}){
 const {height}=useVideoConfig();const frame=useCurrentFrame();const scenes=createScenes(post,prefs);const index=Math.max(0,scenes.filter(s=>frame>=s.start).length-1);const scene=scenes[index];const local=frame-scene.start;const fade=reduced?1:interpolate(local,[0,14],[0,1],{extrapolateRight:'clamp'});const rise=reduced?0:interpolate(local,[0,20],[20,0],{extrapolateRight:'clamp'});const units=revealUnits(scene.text,prefs.reveal);const count=visibleUnitCount(scene.text,prefs.reveal,local,prefs);const foreground=dark?'#f0eee8':'#29302a';
 return <AbsoluteFill style={{background:dark?'#161918':'#eeeae1',color:foreground,fontFamily:'DM Sans, Arial, sans-serif'}}>
 <AbsoluteFill style={{overflow:'hidden',height:scene.cover?'100%':'43%',opacity:prefs.focus?.16:scene.cover?1:.45}}><Img src={post.cover.url} style={{width:'100%',height:'100%',objectFit:'cover',objectPosition:post.cover.position||'center',transform:`scale(${reduced?1:1.08+Math.sin(frame/230)*.04}) translateX(${reduced?0:Math.sin(frame/180)*6}px)`}} onError={()=>{}}/><AbsoluteFill style={{background:scene.cover?'linear-gradient(180deg,#0005,#0008 25%,#000b 65%,#000d)':`linear-gradient(180deg,transparent,${dark?'#161918':'#eeeae1'})`}}/></AbsoluteFill>
 {!scene.cover&&<div style={{position:'absolute',top:115,left:35,right:35,height:190,opacity:prefs.focus?.3:1}}><MotionScene post={post} frame={reduced?30:frame} reduced={reduced}/></div>}
 <div style={{position:'absolute',top:scene.cover?(prefs.focus?Math.min(215,height*.26):Math.min(360,height*.4)):(prefs.focus?Math.min(230,height*.27):Math.min(330,height*.36)),left:30,right:immersive?78:30,color:scene.cover&&!prefs.focus?'white':foreground,opacity:fade,transform:`translateY(${rise}px)`}}><span style={{fontSize:12,fontWeight:700,letterSpacing:2.4,color:scene.cover&&!prefs.focus?'#f7d9ba':dark?'#e6b995':post.accent}}>{scene.kicker.toLocaleUpperCase('tr-TR')}</span><h2 style={{fontFamily:'Manrope, sans-serif',fontSize:scene.cover?(scene.title.length>65?31:35):25,lineHeight:1.2,letterSpacing:-1,margin:'16px 0 22px',textWrap:'balance'}}>{scene.title}</h2><p style={{fontSize:(prefs.focus?26:23)*prefs.textSize,lineHeight:1.55,margin:0,fontWeight:prefs.focus?550:450,whiteSpace:'pre-wrap',overflowWrap:'anywhere'}} aria-label={scene.text}>{prefs.focus?units.map((unit:string,i:number)=><span aria-hidden="true" key={i} style={{opacity:i<count?1:0,color:i===count-1?(dark?'#f4b58e':'#bd4c25'):undefined}}>{unit}</span>):scene.text}</p></div>
 <div style={{position:'absolute',bottom:112,left:34,right:34,display:'flex',justifyContent:'space-between',fontSize:12,color:scene.cover&&!prefs.focus?'#fffd':foreground,opacity:.65}}><span>{prefs.focus?'KENDİ RİTMİNDE':scene.cover?'BİRAZ DAHA YAKINDAN':'KÜÇÜK BİR KEŞİF'}</span><span>{index+1} / {scenes.length}</span></div>
 </AbsoluteFill>;
}
export function FilmPlayer({post,active=true,story=false,onEnd,onClose,onSeen,onSave,saved=false,onShare}:{post:Post;active?:boolean;story?:boolean;onEnd?:()=>void;onClose?:()=>void;onSeen?:()=>void;onSave?:()=>void;saved?:boolean;onShare?:()=>void}){
 const stage=useRef<HTMLDivElement>(null);const [compositionHeight,setCompositionHeight]=useState(800);
 useEffect(()=>{const el=stage.current;if(!el)return;const observer=new ResizeObserver(([entry])=>{const {width,height}=entry.contentRect;if(width>0)setCompositionHeight(Math.max(720,Math.round(height/width*450)));});observer.observe(el);return()=>observer.disconnect();},[]);
 const {prefs,setPrefs,dark}=usePreferences();const player=useRef<PlayerRef>(null);const [playing,setPlaying]=useState(false),[frame,setFrame]=useState(0),[panel,setPanel]=useState(false),[soundEnabled,setSoundEnabled]=useState(false),[audioNote,setAudioNote]=useState('');
 const [voices,setVoices]=useState<SpeechSynthesisVoice[]>([]);const sound=useRef<AmbientSound|null>(null),owner=useRef(Symbol('narration')),holding=useRef(false),resumeAfterPanel=useRef(false),panelScene=useRef(0),settingsRef=useRef<HTMLDivElement>(null),returnFocus=useRef<HTMLElement|null>(null);const reduced=useMemo(()=>matchMedia('(prefers-reduced-motion: reduce)').matches,[]);
 const scenes=useMemo(()=>createScenes(post,prefs),[post,prefs]);const duration=scenes.reduce((sum,s)=>sum+s.frames,0);const current=Math.max(0,scenes.filter(s=>frame>=s.start).length-1);const scene=scenes[current];const endRef=useRef(onEnd),seenRef=useRef(onSeen);endRef.current=onEnd;seenRef.current=onSeen;const voiced=voices.find(v=>v.lang.toLowerCase().startsWith('tr'));
 const stopSpeech=()=>{if(speechOwner===owner.current){speechSynthesis.cancel();speechOwner=undefined;}};
 useEffect(()=>{if(!('speechSynthesis'in window))return;const load=()=>setVoices(speechSynthesis.getVoices());load();speechSynthesis.addEventListener('voiceschanged',load);return()=>{speechSynthesis.removeEventListener('voiceschanged',load);stopSpeech();};},[]);
 useEffect(()=>{const p=player.current;if(!p)return;const onFrame=(e:{detail:{frame:number}})=>setFrame(e.detail.frame);const onPlay=()=>setPlaying(true),onPause=()=>setPlaying(false),ended=()=>{seenRef.current?.();setPlaying(false);endRef.current?.();};p.addEventListener('frameupdate',onFrame);p.addEventListener('play',onPlay);p.addEventListener('pause',onPause);p.addEventListener('ended',ended);const visibility=()=>{if(document.hidden){p.pause();stopSpeech();void sound.current?.pause();}};document.addEventListener('visibilitychange',visibility);return()=>{p.removeEventListener('frameupdate',onFrame);p.removeEventListener('play',onPlay);p.removeEventListener('pause',onPause);p.removeEventListener('ended',ended);document.removeEventListener('visibilitychange',visibility);stopSpeech();sound.current?.close();sound.current=null;};},[post.id]);
 useEffect(()=>{if(active&&!reduced)player.current?.play();else{player.current?.pause();stopSpeech();void sound.current?.pause();}},[active,reduced]);
 useEffect(()=>{if(!sound.current)return;sound.current.setVolume(prefs.musicVolume);if(active&&playing&&!panel&&prefs.music&&soundEnabled)void sound.current.play().catch(()=>setAudioNote('Müziği başlatmak için ses düğmesine yeniden dokun.'));else void sound.current.pause();},[active,playing,panel,prefs.music,prefs.musicVolume,soundEnabled]);
 useEffect(()=>{if(!prefs.narration||!soundEnabled||!active||!playing||panel||!voiced){stopSpeech();return;}speechSynthesis.cancel();speechOwner=owner.current;const utterance=new SpeechSynthesisUtterance(`${scene.title}. ${scene.text}`);utterance.lang='tr-TR';utterance.voice=voiced;utterance.rate=.95;utterance.onerror=e=>{if(e.error!=='canceled'&&e.error!=='interrupted')setAudioNote('Seslendirme başlayamadı. Cihazının Türkçe sesini kontrol edebilirsin.');};speechSynthesis.speak(utterance);return stopSpeech;},[scene.start,scene.text,active,playing,panel,soundEnabled,prefs.narration,voiced]);
 const goTo=(index:number)=>{stopSpeech();player.current?.seekTo(scenes[index].start+(playing?0:18));};
 const seek=(direction:number)=>{stopSpeech();const target=current+direction;if(target>=scenes.length){seenRef.current?.();if(onEnd)onEnd();else{player.current?.seekTo(0);player.current?.play();}return;}goTo(Math.max(0,target));};
 const togglePanel=()=>{if(panel){setPanel(false);requestAnimationFrame(()=>returnFocus.current?.focus());if(resumeAfterPanel.current&&active)player.current?.play();}else{returnFocus.current=document.activeElement as HTMLElement;panelScene.current=current;resumeAfterPanel.current=playing;player.current?.pause();setPanel(true);}};
 useEffect(()=>{if(panel)settingsRef.current?.querySelector<HTMLButtonElement>('button')?.focus();},[panel]);
 const enableAudio=()=>{if(soundEnabled){setSoundEnabled(false);return;}setSoundEnabled(true);if(prefs.music){try{if(!sound.current)sound.current=new AmbientSound(prefs.musicVolume);void sound.current.play().catch(()=>setAudioNote('Bu tarayıcı müziği başlatamadı.'));}catch{setAudioNote('Bu tarayıcı müzik üretimini desteklemiyor.');}}if(!prefs.music&&!prefs.narration){setAudioNote('Ses ayarlarından seslendirmeyi veya müziği açabilirsin.');if(!panel)togglePanel();}else setAudioNote('');};
 const toggleMusic=()=>{setPrefs({music:!prefs.music});if(!prefs.music){setSoundEnabled(true);try{if(!sound.current)sound.current=new AmbientSound(prefs.musicVolume);void sound.current.play().catch(()=>{});}catch{setAudioNote('Müzik bu tarayıcıda kullanılamıyor.');}}};
 return <div ref={stage} className={`film-player ${story?'is-story':''} ${prefs.focus?'focus-active':''} ${dark?'film-dark':'film-light'}`} onKeyDown={e=>{if((e.target as HTMLElement).closest('input,button,select'))return;if(e.key==='ArrowRight')seek(1);if(e.key==='ArrowLeft')seek(-1);}}>
 <Player ref={player} component={KnowledgeFilm} inputProps={{post,prefs,dark,reduced,immersive:!story}} durationInFrames={duration} fps={30} compositionWidth={450} compositionHeight={compositionHeight} style={{width:'100%',height:'100%'}} controls={false} autoPlay={false} loop={false} clickToPlay={false} doubleClickToFullscreen={false} acknowledgeRemotionLicense errorFallback={()=> <div className="film-error">Anlatım yüklenemedi. Gönderiyi okuyarak devam edebilirsin.</div>}/>
 <div className="film-top" inert={panel}><div className="story-progress">{scenes.map((s,i)=><button aria-label={`${i+1}. sahneye git`} key={i} onClick={()=>goTo(i)}><i style={{width:`${Math.min(100,Math.max(0,(frame-s.start)/s.frames*100))}%`}}/></button>)}</div><div className="film-header"><Avatar post={post}/><span>{post.account}<small>{post.category}</small></span><IconButton label="Odak modu ayarları" active={prefs.focus} onClick={togglePanel}><Focus size={20}/></IconButton><IconButton label={playing?'Anlatımı duraklat':'Anlatımı oynat'} onClick={()=>{if(playing)player.current?.pause();else{if(frame>=duration-1)player.current?.seekTo(0);player.current?.play();}}}>{playing?<Pause size={20}/>:<Play size={20}/>}</IconButton>{onClose&&<IconButton label="Anlatımı kapat" onClick={onClose}><X size={20}/></IconButton>}</div></div>
 {story&&!panel&&<div className="story-touch" onPointerDown={()=>{holding.current=playing;player.current?.pause();}} onPointerUp={()=>{if(holding.current)player.current?.play();holding.current=false;}} onPointerCancel={()=>{holding.current=false;}}><button aria-label="Önceki anlatım kartı" onClick={()=>seek(-1)}/><button aria-label="Sonraki anlatım kartı" onClick={()=>seek(1)}/></div>}
 <div className="film-bottom" inert={panel}><div className="film-utilities"><IconButton label={soundEnabled?'Sesi kapat':'Sesi başlat'} active={soundEnabled} onClick={enableAudio}>{soundEnabled?<Volume2 size={19}/>:<VolumeX size={19}/>}</IconButton>{onSave&&<IconButton label={saved?'Kaydı kaldır':'Daha sonra okumak için kaydet'} active={saved} onClick={onSave}><Bookmark size={19} fill={saved?'currentColor':'none'}/></IconButton>}{onShare&&<IconButton label="Anlatımı paylaş" onClick={onShare}><Send size={19}/></IconButton>}</div><div className="film-nav"><IconButton label="Önceki sahne" onClick={()=>seek(-1)}><ChevronLeft/></IconButton><span>{current+1} / {scenes.length}</span><IconButton label="Sonraki sahne" onClick={()=>seek(1)}><ChevronRight/></IconButton></div></div>
 {audioNote&&!panel&&<p className="film-audio-note" role="status">{audioNote}</p>}
 {panel&&<div ref={settingsRef} className="film-settings swiper-no-swiping swiper-no-mousewheel" role="region" aria-label="Anlatım ayarları" onKeyDown={e=>{if(e.key==='Escape'){e.preventDefault();e.stopPropagation();togglePanel();}}}><header><span><Focus size={18}/> Kendi ritminde</span><IconButton label="Anlatım ayarlarını kapat" onClick={togglePanel}><X size={20}/></IconButton></header><div className="film-settings-scroll"><FocusSettings compact/><div className="audio-settings"><h3>Biraz da ses</h3><label className="switch-row"><span><strong><Volume2 size={17}/> Türkçe seslendirme</strong><small>{voiced?'Cihazının Türkçe sesiyle okunur.':'Bu cihazda Türkçe ses bulunamadı.'}</small></span><input aria-label="Türkçe seslendirme" type="checkbox" role="switch" disabled={!voiced} checked={prefs.narration} onChange={e=>{setPrefs({narration:e.target.checked});setSoundEnabled(true);}}/></label><label className="switch-row"><span><strong><Music2 size={17}/> Hafif müzik</strong><small>Learnie için üretilen sakin tonlar.</small></span><input aria-label="Hafif müzik" type="checkbox" role="switch" checked={prefs.music} onChange={toggleMusic}/></label>{prefs.music&&<label className="setting-field"><span>Müzik seviyesi <output>%{prefs.musicVolume}</output></span><input aria-label="Müzik seviyesi" type="range" min="0" max="40" value={prefs.musicVolume} onChange={e=>setPrefs({musicVolume:Number(e.target.value)})}/></label>}<p className="preference-note">Ses tercihlerin saklanır. Yeni bir anlatımda sesi başlatmak için hoparlöre dokunabilirsin.</p></div>{audioNote&&<p className="preference-note" role="status">{audioNote}</p>}</div><button className="primary-button settings-done" onClick={()=>{player.current?.seekTo(scenes[panelScene.current]?.start||0);resumeAfterPanel.current=true;togglePanel();}}><Play size={16}/> Bu ayarlarla devam et</button></div>}
 </div>;
}
export default function Reels({posts,user,onLike,onSave,onShare,onOpen,onSeen,onClose,onComments,visible=true}:{posts:Post[];user:UserState;onLike:(id:string)=>void;onSave:(id:string)=>void;onShare:(p:Post)=>void;onOpen:(p:Post)=>void;onSeen:(id:string)=>void;onClose:()=>void;onComments:(p:Post)=>void;visible?:boolean}){
 const [active,setActive]=useState(0);const [items,setItems]=useState(()=>shuffle(posts));
 return <div className="reels-view"><button className="reels-close" aria-label="Reels akışını kapat" onClick={onClose}><X size={25}/></button><Swiper direction="vertical" modules={[Virtual,Mousewheel,Keyboard,A11y]} virtual mousewheel={{forceToAxis:true}} keyboard={{enabled:visible}} onSlideChange={s=>{setActive(s.activeIndex);if(items[s.activeIndex])onSeen(items[s.activeIndex].id);if(s.activeIndex>=items.length-3)setItems(v=>[...v,...shuffle(posts)]);}} className="reels-swiper">{items.map((p,i)=><SwiperSlide key={`${p.id}-${i}`} virtualIndex={i}><div className="reel-shell" inert={i!==active}>{Math.abs(active-i)<=1&&<FilmPlayer key={`${p.id}-${i}`} post={p} active={active===i&&visible}/>}<div className="reel-actions"><IconButton label="Reels beğen" active={user.liked.includes(p.id)} onClick={()=>onLike(p.id)}><Heart fill={user.liked.includes(p.id)?'currentColor':'none'}/></IconButton><IconButton label={user.saved.includes(p.id)?'Reels kaydını kaldır':'Reels kaydet'} active={user.saved.includes(p.id)} onClick={()=>onSave(p.id)}><Bookmark fill={user.saved.includes(p.id)?'currentColor':'none'}/></IconButton><IconButton label="Reels yorumları" onClick={()=>onComments(p)}><MessageCircle/></IconButton><IconButton label="Reels paylaş" onClick={()=>onShare(p)}><Send/></IconButton><IconButton label="Anlatımı oku" onClick={()=>onOpen(p)}><BookOpen/></IconButton></div></div></SwiperSlide>)}</Swiper><span className="reels-hint">Bir sonraki merak <ChevronDown size={17}/></span></div>;
}
