import {useEffect,useMemo,useRef,useState} from 'react';
import {AbsoluteFill,Img,interpolate,useCurrentFrame,useVideoConfig} from 'remotion';
import {Player,type PlayerRef} from '@remotion/player';
import {Swiper,SwiperSlide} from 'swiper/react';
import {Virtual,Mousewheel,Keyboard,A11y} from 'swiper/modules';
import {Bookmark,ChevronDown,ChevronLeft,ChevronRight,Heart,Pause,Play,Send,X,BookOpen} from 'lucide-react';
import {Avatar,IconButton} from './components';
import type {Post,UserState} from './types';
const sceneFrames=(post:Post)=>[210,...post.slides.map(s=>Math.max(240,Math.ceil(s.text.split(' ').length/2.7*30)))];
function KnowledgeFilm({post,reduced=false}:{post:Post;reduced?:boolean}){
 const frame=useCurrentFrame();const {width}=useVideoConfig();const lengths=sceneFrames(post);let start=0;let index=0;while(index<lengths.length-1&&frame>=start+lengths[index]){start+=lengths[index];index++;}const local=frame-start;const opacity=reduced?1:interpolate(local,[0,12],[0,1],{extrapolateRight:'clamp'});const rise=reduced?0:interpolate(local,[0,18],[24,0],{extrapolateRight:'clamp'});const slide=post.slides[index-1];
 return <AbsoluteFill style={{background:index===0?'#191c1b':['#f3eee4','#e5eee7','#efeaf5'][index%3],color:index===0?'white':'#202820',fontFamily:'Arial, sans-serif'}}>
 {index===0?<><Img src={post.cover.url} style={{width:'100%',height:'100%',objectFit:'cover',transform:`scale(${reduced?1:1+frame/18000})`}} onError={()=>{}}/><AbsoluteFill style={{background:'linear-gradient(180deg,rgba(0,0,0,.05) 10%,rgba(0,0,0,.1) 30%,rgba(0,0,0,.84) 100%)'}}/><div style={{position:'absolute',left:36,right:36,bottom:130,opacity,transform:`translateY(${rise}px)`}}><span style={{fontSize:15,letterSpacing:3,fontWeight:700}}>{post.category.toLocaleUpperCase('tr-TR')}</span><h1 style={{fontSize:width*.092,lineHeight:1.09,letterSpacing:-1.5,margin:'18px 0'}}>{post.title}</h1><p style={{fontSize:19,lineHeight:1.55,opacity:.85}}>{post.subtitle}</p></div></>:<><div style={{position:'absolute',left:36,top:110,right:36,display:'flex',justifyContent:'space-between',fontSize:15,letterSpacing:2}}><span>{post.category.toLocaleUpperCase('tr-TR')}</span><span>{String(index).padStart(2,'0')}</span></div><div style={{position:'absolute',left:36,right:36,top:205,opacity,transform:`translateY(${rise}px)`}}><span style={{fontSize:14,fontWeight:700,color:post.accent}}>{slide.kicker?.toLocaleUpperCase('tr-TR')||'BİRAZ DAHA YAKINDAN'}</span><h2 style={{fontSize:38,lineHeight:1.15,letterSpacing:-1.3,margin:'20px 0 28px'}}>{slide.title}</h2><p style={{fontSize:24,lineHeight:1.6,margin:0}}>{slide.text}</p></div><div style={{position:'absolute',bottom:135,left:36,right:36,height:2,background:'rgba(0,0,0,.1)'}}><div style={{height:2,width:`${local/lengths[index]*100}%`,background:post.accent}}/></div></>}
 <div style={{position:'absolute',left:36,bottom:60,fontWeight:800,fontSize:23,letterSpacing:-1}}>learnie<span style={{color:'#ed6b39'}}>.</span></div>
 </AbsoluteFill>;
}
export function FilmPlayer({post,active=true,story=false,onEnd,onClose,onSeen}:{post:Post;active?:boolean;story?:boolean;onEnd?:()=>void;onClose?:()=>void;onSeen?:()=>void}){
 const player=useRef<PlayerRef>(null);const [playing,setPlaying]=useState(active);const [frame,setFrame]=useState(0);const [holding,setHolding]=useState(false);const [failure,setFailure]=useState(false);const reduced=useMemo(()=>matchMedia('(prefers-reduced-motion: reduce)').matches,[]);const lengths=sceneFrames(post),duration=lengths.reduce((a,b)=>a+b,0);const starts=lengths.map((_,i)=>lengths.slice(0,i).reduce((a,b)=>a+b,0));const current=Math.max(0,starts.filter(x=>frame>=x).length-1);const endRef=useRef(onEnd),seenRef=useRef(onSeen);endRef.current=onEnd;seenRef.current=onSeen;
 useEffect(()=>{const p=player.current;if(!p)return;const onFrame=(e:{detail:{frame:number}})=>setFrame(e.detail.frame);const onPlay=()=>setPlaying(true);const onPause=()=>setPlaying(false);const ended=()=>{seenRef.current?.();endRef.current?.();};p.addEventListener('frameupdate',onFrame);p.addEventListener('play',onPlay);p.addEventListener('pause',onPause);p.addEventListener('ended',ended);const visibility=()=>{if(document.hidden)p.pause();};document.addEventListener('visibilitychange',visibility);return()=>{p.removeEventListener('frameupdate',onFrame);p.removeEventListener('play',onPlay);p.removeEventListener('pause',onPause);p.removeEventListener('ended',ended);document.removeEventListener('visibilitychange',visibility);};},[post.id]);
 useEffect(()=>{if(active&&!reduced)player.current?.play();else player.current?.pause();},[active,reduced]);
 const seek=(direction:number)=>{const target=current+direction;if(target>=lengths.length){seenRef.current?.();onEnd?.();return;}player.current?.seekTo(starts[Math.max(0,target)]);};
 return <div className={`film-player ${story?'is-story':''}`} onKeyDown={e=>{if(e.key==='ArrowRight')seek(1);if(e.key==='ArrowLeft')seek(-1);}}>
 <Player ref={player} component={KnowledgeFilm} inputProps={{post,reduced}} durationInFrames={duration} fps={30} compositionWidth={450} compositionHeight={800} style={{width:'100%',height:'100%'}} controls={false} autoPlay={active&&!reduced} loop={!story} clickToPlay={false} doubleClickToFullscreen={false} acknowledgeRemotionLicense errorFallback={()=> <div className="film-error">Anlatım yüklenemedi. Gönderiyi okuyarak devam edebilirsin.</div>}/>
 <div className="film-top"><div className="story-progress">{lengths.map((length,i)=><span key={i}><i style={{width:`${Math.min(100,Math.max(0,(frame-starts[i])/length*100))}%`}}/></span>)}</div><div className="film-header"><Avatar post={post}/><span>{post.account}<small>{post.category}</small></span><IconButton label={playing?'Anlatımı duraklat':'Anlatımı oynat'} onClick={()=>playing?player.current?.pause():player.current?.play()}>{playing?<Pause size={20}/>:<Play size={20}/>}</IconButton>{onClose&&<IconButton label="Hikâyeyi kapat" onClick={onClose}><X/></IconButton>}</div></div>
 {story&&<div className="story-touch" onPointerDown={()=>{setHolding(playing);player.current?.pause();}} onPointerUp={()=>{if(holding)player.current?.play();setHolding(false);}} onPointerCancel={()=>setHolding(false)}><button aria-label="Önceki hikâye kartı" onClick={()=>seek(-1)}/><button aria-label="Sonraki hikâye kartı" onClick={()=>seek(1)}/></div>}
 <div className="film-nav"><IconButton label="Önceki sahne" onClick={()=>seek(-1)}><ChevronLeft/></IconButton><span>{current+1} / {lengths.length}</span><IconButton label="Sonraki sahne" onClick={()=>seek(1)}><ChevronRight/></IconButton></div>
 </div>;
}
export default function Reels({posts,user,onLike,onSave,onShare,onOpen,onSeen}:{posts:Post[];user:UserState;onLike:(id:string)=>void;onSave:(id:string)=>void;onShare:(p:Post)=>void;onOpen:(p:Post)=>void;onSeen:(id:string)=>void}){
 const [active,setActive]=useState(0);const [items,setItems]=useState(()=>posts.slice());
 return <div className="reels-view"><Swiper direction="vertical" modules={[Virtual,Mousewheel,Keyboard,A11y]} virtual mousewheel={{forceToAxis:true}} keyboard={{enabled:true}} onSlideChange={s=>{setActive(s.activeIndex);onSeen(items[s.activeIndex].id);if(s.activeIndex>=items.length-3)setItems(v=>[...v,...posts]);}} className="reels-swiper">{items.map((p,i)=><SwiperSlide key={`${p.id}-${i}`} virtualIndex={i}><div className="reel-shell">{Math.abs(active-i)<=1&&<FilmPlayer key={`${p.id}-${i}`} post={p} active={active===i}/>}<div className="reel-actions"><IconButton label="Reels beğen" active={user.liked.includes(p.id)} onClick={()=>onLike(p.id)}><Heart fill={user.liked.includes(p.id)?'currentColor':'none'}/></IconButton><IconButton label="Reels kaydet" active={user.saved.includes(p.id)} onClick={()=>onSave(p.id)}><Bookmark fill={user.saved.includes(p.id)?'currentColor':'none'}/></IconButton><IconButton label="Reels paylaş" onClick={()=>onShare(p)}><Send/></IconButton><IconButton label="Anlatımı oku" onClick={()=>onOpen(p)}><BookOpen/></IconButton></div></div></SwiperSlide>)}</Swiper><span className="reels-hint">Bir sonraki merak <ChevronDown size={17}/></span></div>;
}
