import {useEffect,useMemo,useRef,useState} from 'react';
import {AbsoluteFill,Img,interpolate,useCurrentFrame,useVideoConfig} from 'remotion';
import {Player,type PlayerRef} from '@remotion/player';
import type {Swiper as SwiperInstance} from 'swiper';
import {useBackGesture} from './useBackGesture';
import {Swiper,SwiperSlide} from 'swiper/react';
import {Virtual,Mousewheel,Keyboard,A11y} from 'swiper/modules';
import {Bookmark,ChevronUp,ChevronDown,ChevronLeft,ChevronRight,Heart,Pause,Play,Send,X,BookOpen,Focus,Volume2,VolumeX,Music2,MessageCircle,Eye,EyeOff} from 'lucide-react';
import VideoEmbed,{VideoPoster} from './VideoEmbed';
import {engagement,formatCount,reelQueue} from './social.mjs';
import {Avatar,IconButton} from './components';
import {FocusSettings,usePreferences,type Preferences} from './Preferences';
import {createScenes,revealUnits,visibleUnitCount} from './preferences.mjs';
import {MotionScene} from './MotionScene';
import {AmbientSound} from './audio';
import {shuffle} from './engine.mjs';
import type {Post,UserState} from './types';
import SpeechSettings,{useTurkishVoices} from './SpeechSettings';
import {chooseVoice,spokenUnitCount} from './narration.mjs';
import {useNarration} from './useNarration';
function KnowledgeFilm({post,prefs,dark,reduced=false,immersive=false,speech}:{speech?:{start:number;chars:number};post:Post;prefs:Preferences;dark:boolean;reduced?:boolean;immersive?:boolean}){
 const {height}=useVideoConfig();const frame=useCurrentFrame();const scenes=createScenes(post,prefs);const index=Math.max(0,scenes.filter(s=>frame>=s.start).length-1);const scene=scenes[index];const local=frame-scene.start;const fade=reduced?1:interpolate(local,[0,14],[0,1],{extrapolateRight:'clamp'});const rise=reduced?0:interpolate(local,[0,20],[20,0],{extrapolateRight:'clamp'});const units=revealUnits(scene.text,prefs.reveal);const tracking=!!speech&&speech.start===scene.start;const count=tracking?spokenUnitCount(scene.text,prefs.reveal,speech.chars):visibleUnitCount(scene.text,prefs.reveal,local,prefs);const foreground=post.art?.ink||'#24211e';const paper=post.art?.paper||'#f1ebdf';const photo=post.art?.kind==='photo'||!post.art;
 return <AbsoluteFill style={{background:paper,color:foreground,fontFamily:`${post.art?.font||'DM Sans'}, Arial, sans-serif`}}>
 {photo&&<AbsoluteFill style={{overflow:'hidden',height:scene.cover?'100%':'43%',opacity:prefs.focus?.16:scene.cover?1:.45}}><Img src={post.cover.url} style={{width:'100%',height:'100%',objectFit:'cover',objectPosition:post.cover.position||'center',transform:`scale(${reduced?1:1.08+Math.sin(frame/230)*.04}) translateX(${reduced?0:Math.sin(frame/180)*6}px)`}} onError={()=>{}}/><AbsoluteFill style={{background:scene.cover?'linear-gradient(180deg,#0005,#0008 25%,#000b 65%,#000d)':`linear-gradient(180deg,transparent,${paper})`}}/></AbsoluteFill>}
 {!scene.cover&&<div style={{position:'absolute',top:115,left:35,right:35,height:190,opacity:prefs.focus?.3:1}}><MotionScene post={post} frame={reduced?30:frame} reduced={reduced}/></div>}
 <div style={{position:'absolute',top:scene.cover?(prefs.focus?Math.min(215,height*.26):Math.min(360,height*.4)):(prefs.focus?Math.min(230,height*.27):Math.min(330,height*.36)),left:30,right:immersive?78:30,color:scene.cover&&photo&&!prefs.focus?'white':foreground,opacity:fade,transform:`translateY(${rise}px)`}}><span style={{fontSize:12,fontWeight:700,letterSpacing:2.4,color:'inherit',opacity:.6}}>{scene.kicker.toLocaleUpperCase('tr-TR')}</span>{scene.cover&&<h2 style={{fontFamily:`${post.art?.font||'Manrope'}, sans-serif`,fontSize:scene.cover?(scene.title.length>65?31:35):25,lineHeight:1.2,letterSpacing:-1,margin:'16px 0 22px',textWrap:'balance'}}>{scene.title}</h2>}<p style={{fontFamily:['Bebas Neue','Oswald'].includes(post.art?.font||'')?'DM Sans, Arial, sans-serif':`${post.art?.font||'DM Sans'}, Arial, sans-serif`,fontSize:(prefs.focus?26:23)*prefs.textSize,lineHeight:1.55,margin:0,fontWeight:prefs.focus?550:450,whiteSpace:'pre-wrap',overflowWrap:'anywhere'}} aria-label={scene.text}>{prefs.focus||tracking?units.map((unit:string,i:number)=><span aria-hidden="true" key={i} style={{opacity:i<count?1:0,color:'inherit'}}>{unit}</span>):scene.text}</p></div>
 <div style={{position:'absolute',bottom:112,left:34,right:34,display:'flex',justifyContent:'space-between',fontSize:12,color:scene.cover&&photo&&!prefs.focus?'#fffd':foreground,opacity:.65}}><span>{prefs.focus?'KENDİ RİTMİNDE':scene.cover?'BİRAZ DAHA YAKINDAN':'KÜÇÜK BİR KEŞİF'}</span><span>{index+1} / {scenes.length}</span></div>
 </AbsoluteFill>;
}
export function FilmPlayer({post,active=true,story=false,onEnd,onClose,onSeen,onSave,saved=false,onShare,onAccount}:{post:Post;active?:boolean;story?:boolean;onEnd?:()=>void;onClose?:()=>void;onSeen?:()=>void;onSave?:()=>void;saved?:boolean;onShare?:()=>void;onAccount?:()=>void}){
 const stage=useRef<HTMLDivElement>(null),player=useRef<PlayerRef>(null),sound=useRef<AmbientSound|null>(null);
 const [compositionHeight,setCompositionHeight]=useState(800),[frame,setFrame]=useState(0),[playing,setPlaying]=useState(false),[panel,setPanel]=useState(false),[audioNote,setAudioNote]=useState(''),[replay,setReplay]=useState(0);
 const {prefs,setPrefs,dark}=usePreferences();const [soundEnabled,setSoundEnabled]=useState(prefs.narration||prefs.music);
 const voices=useTurkishVoices(),voiced=chooseVoice(voices,prefs.voiceURI),narrating=prefs.narration&&soundEnabled&&!!voiced;
 const holding=useRef(false),settingsRef=useRef<HTMLDivElement>(null),returnFocus=useRef<HTMLElement|null>(null),endRef=useRef(onEnd),seenRef=useRef(onSeen);endRef.current=onEnd;seenRef.current=onSeen;
 const reduced=useMemo(()=>matchMedia('(prefers-reduced-motion: reduce)').matches,[]);
 const scenes=useMemo(()=>createScenes(post,prefs),[post,prefs]),duration=scenes.reduce((sum,s)=>sum+s.frames,0);
 const current=Math.max(0,scenes.filter(s=>frame>=s.start).length-1),scene=scenes[current];
 const goTo=(index:number)=>{const next=scenes[Math.max(0,Math.min(index,scenes.length-1))];setReplay(n=>n+1);setFrame(next.start+18);player.current?.seekTo(next.start+18);};
 const finish=()=>{setPlaying(false);seenRef.current?.();endRef.current?.();};
 const advance=()=>{if(current+1<scenes.length)goTo(current+1);else{player.current?.seekTo(duration-1);setFrame(duration-1);finish();}};
 const speechText=`${scene.title?scene.title+'. ':''}${scene.text}`;
 const spoken=useNarration({sceneKey:`${post.id}:${scene.start}:${replay}`,text:speechText,enabled:narrating,running:active&&playing&&!panel,voice:voiced,rate:prefs.speechRate,onEnd:advance,onError:note=>{setAudioNote(note);setPlaying(false);}});
 const speechChars=Math.max(0,spoken-(scene.title?scene.title.length+2:0));
 useEffect(()=>{const el=stage.current;if(!el)return;const observer=new ResizeObserver(([entry])=>{const {width,height}=entry.contentRect;if(width>0)setCompositionHeight(Math.max(720,Math.round(height/width*450)));});observer.observe(el);return()=>observer.disconnect();},[]);
 useEffect(()=>{const p=player.current;if(!p)return;const onFrame=(e:{detail:{frame:number}})=>setFrame(e.detail.frame);const ended=()=>{setPlaying(false);seenRef.current?.();endRef.current?.();};p.addEventListener('frameupdate',onFrame);p.addEventListener('ended',ended);const visibility=()=>{if(document.hidden)setPlaying(false);};document.addEventListener('visibilitychange',visibility);return()=>{p.removeEventListener('frameupdate',onFrame);p.removeEventListener('ended',ended);document.removeEventListener('visibilitychange',visibility);sound.current?.close();sound.current=null;};},[post.id]);
 useEffect(()=>{setPlaying(active&&!reduced);},[active,reduced]);
 useEffect(()=>{const p=player.current;if(!p)return;if(active&&playing&&!panel&&!narrating)p.play();else p.pause();},[active,playing,panel,narrating]);
 useEffect(()=>{if(narrating){const progress=speechText.length?spoken/speechText.length:0;player.current?.seekTo(Math.min(scene.start+scene.frames-2,scene.start+18+Math.floor(progress*(scene.frames-22))));}},[narrating,spoken,scene.start,scene.frames,speechText.length]);
 useEffect(()=>{if(!prefs.music||!soundEnabled||!active||!playing||panel){void sound.current?.pause();return;}try{if(!sound.current)sound.current=new AmbientSound(prefs.musicVolume);sound.current.setVolume(prefs.musicVolume);void sound.current.play().catch(()=>setAudioNote('Müziği başlatmak için ses düğmesine dokun.'));}catch{setAudioNote('Bu cihaz müziği başlatamadı.');}},[prefs.music,prefs.musicVolume,soundEnabled,active,playing,panel]);
 useEffect(()=>{if(!panel)return;const el=settingsRef.current;if(!el)return;const first=el.querySelector<HTMLElement>('button,input,select');first?.focus();},[panel]);
 const togglePlayback=()=>{if(!playing&&frame>=duration-1)goTo(0);setPlaying(v=>!v);};
 const seek=(direction:number)=>{if(current+direction>=scenes.length){if(onEnd)finish();else{goTo(0);setPlaying(true);}return;}goTo(current+direction);};
 const togglePanel=()=>{if(panel){setPanel(false);requestAnimationFrame(()=>returnFocus.current?.focus());}else{returnFocus.current=document.activeElement as HTMLElement;setPanel(true);}};
 const enableAudio=()=>{if(!prefs.narration&&!prefs.music){setPanel(true);return;}setSoundEnabled(v=>!v);setAudioNote('');if(!soundEnabled)setPlaying(true);};
 return <div ref={stage} className={`film-player ${story?'is-story':''} ${prefs.focus?'focus-active':''} ${dark?'film-dark':'film-light'}`} onKeyDown={e=>{if((e.target as HTMLElement).closest('input,button,select'))return;if(e.key==='ArrowRight')seek(1);if(e.key==='ArrowLeft')seek(-1);}}>
 <Player ref={player} component={KnowledgeFilm} inputProps={{post,prefs,dark,reduced,immersive:!story,speech:narrating?{start:scene.start,chars:speechChars}:undefined}} durationInFrames={duration} fps={30} compositionWidth={450} compositionHeight={compositionHeight} style={{width:'100%',height:'100%'}} controls={false} autoPlay={false} loop={false} clickToPlay={false} doubleClickToFullscreen={false} acknowledgeRemotionLicense errorFallback={()=> <div className="film-error">Anlatım yüklenemedi. Gönderiyi okuyarak devam edebilirsin.</div>}/>
 <div className="film-top" inert={panel}><div className="story-progress">{scenes.map((s,i)=><button aria-label={`${i+1}. sahneye git`} key={i} onClick={()=>goTo(i)}><i style={{width:`${Math.min(100,Math.max(0,(frame-s.start)/s.frames*100))}%`}}/></button>)}</div><div className="film-header"><button className="film-account" onClick={onAccount} aria-label={`${post.account} profilini aç`}><Avatar post={post}/><span>{post.account}<small>{post.category}</small></span></button><IconButton label="Odak modu ayarları" active={prefs.focus} onClick={togglePanel}><Focus size={20}/></IconButton><IconButton label={playing?'Anlatımı duraklat':'Anlatımı oynat'} onClick={togglePlayback}>{playing?<Pause size={20}/>:<Play size={20}/>}</IconButton>{onClose&&<IconButton label="Anlatımı kapat" onClick={onClose}><X size={20}/></IconButton>}</div></div>
 {story&&!panel&&<div className="story-touch" onPointerDown={()=>{holding.current=playing;setPlaying(false);}} onPointerUp={()=>{if(holding.current)setPlaying(true);holding.current=false;}} onPointerCancel={()=>{holding.current=false;}}><button aria-label="Önceki anlatım kartı" onClick={()=>seek(-1)}/><button aria-label="Sonraki anlatım kartı" onClick={()=>seek(1)}/></div>}
 <div className="film-bottom" inert={panel}><div className="film-utilities"><IconButton label={soundEnabled?'Sesi kapat':'Sesi başlat'} active={soundEnabled} onClick={enableAudio}>{soundEnabled?<Volume2 size={19}/>:<VolumeX size={19}/>}</IconButton>{onSave&&<IconButton label={saved?'Koleksiyonları düzenle':'Daha sonra okumak için kaydet'} active={saved} onClick={onSave}><Bookmark size={19} fill={saved?'currentColor':'none'}/></IconButton>}{onShare&&<IconButton label="Anlatımı paylaş" onClick={onShare}><Send size={19}/></IconButton>}</div><div className="film-nav"><IconButton label="Önceki sahne" onClick={()=>seek(-1)}><ChevronLeft/></IconButton><span>{current+1} / {scenes.length}</span><IconButton label="Sonraki sahne" onClick={()=>seek(1)}><ChevronRight/></IconButton></div></div>
 {audioNote&&!panel&&<p className="film-audio-note" role="status">{audioNote}</p>}
 {panel&&<div ref={settingsRef} className="film-settings swiper-no-swiping swiper-no-mousewheel" role="region" aria-label="Anlatım ayarları" onKeyDown={e=>{if(e.key==='Escape'){e.preventDefault();e.stopPropagation();togglePanel();}}}><header><span><Focus size={18}/> Kendi ritminde</span><IconButton label="Anlatım ayarlarını kapat" onClick={togglePanel}><X size={20}/></IconButton></header><div className="film-settings-scroll"><FocusSettings compact/><div className="audio-settings"><h3>Biraz da ses</h3><label className="switch-row"><span><strong><Volume2 size={17}/> Türkçe seslendirme</strong><small>Yazı, konuşmayla birlikte ilerler.</small></span><input aria-label="Türkçe seslendirme" type="checkbox" role="switch" disabled={!voiced} checked={prefs.narration} onChange={e=>{setPrefs({narration:e.target.checked});setSoundEnabled(true);}}/></label><SpeechSettings compact/><label className="switch-row"><span><strong><Music2 size={17}/> Hafif müzik</strong></span><input aria-label="Hafif müzik" type="checkbox" role="switch" checked={prefs.music} onChange={e=>{setPrefs({music:e.target.checked});setSoundEnabled(true);}}/></label>{prefs.music&&<label className="setting-field"><span>Müzik seviyesi <output>%{prefs.musicVolume}</output></span><input aria-label="Müzik seviyesi" type="range" min="0" max="40" value={prefs.musicVolume} onChange={e=>setPrefs({musicVolume:Number(e.target.value)})}/></label>}<p className="preference-note">Kelime zamanlaması sunmayan seslerde metin cümle cümle takip edilir.</p></div>{audioNote&&<p className="preference-note" role="status">{audioNote}</p>}</div><button className="primary-button settings-done" onClick={()=>{setPanel(false);setPlaying(true);}}><Play size={16}/> Devam et</button></div>}
 </div>;
}
export default function Reels({posts,user,onLike,onSave,onShare,onOpen,onSeen,onClose,onComments,onAccount,visible=true,initialId}:{initialId?:string;posts:Post[];user:UserState;onLike:(id:string)=>void;onSave:(id:string)=>void;onShare:(p:Post)=>void;onOpen:(p:Post)=>void;onSeen:(id:string)=>void;onClose:()=>void;onComments:(p:Post)=>void;onAccount:(p:Post)=>void;visible?:boolean}){
 const reelsRef=useRef<HTMLDivElement>(null),swiper=useRef<SwiperInstance|null>(null),swipeStart=useRef<{x:number;y:number}|null>(null);useBackGesture(reelsRef,()=>{if(visible)onClose();});
 const [active,setActive]=useState(0),[clean,setClean]=useState(false);const [items,setItems]=useState(()=>reelQueue(posts,initialId));const current=items[active];
 const isVideo=current?.display==='video'&&!!current.video;
 const lastVideo=useRef<Post|undefined>(undefined);if(isVideo)lastVideo.current=current;
 return <div ref={reelsRef} className={`reels-view reels-v2 ${clean?'reels-clean':''}`} onKeyDown={e=>{if(e.key==='Escape'){e.preventDefault();if(clean)setClean(false);else onClose();}}}>
  <header className="reels-toolbar"><button className="reels-back" aria-label="Reels akışını kapat" onClick={onClose}><ChevronLeft size={27}/></button>{!clean&&current&&<button className="reels-account" onClick={()=>onAccount(current)} aria-label={`${current.account} profilini aç`}><Avatar post={current}/><strong>{current.account}</strong></button>}<div className="clean-navigation"><button aria-label="Önceki video" disabled={active===0} onClick={()=>swiper.current?.slidePrev()}><ChevronUp size={21}/></button><button aria-label="Sonraki video" onClick={()=>swiper.current?.slideNext()}><ChevronDown size={21}/></button></div><button className="reels-clean-toggle" aria-label={clean?'Arayüzü göster':'Arayüzü gizle'} aria-pressed={clean} onClick={()=>setClean(v=>!v)}>{clean?<Eye size={22}/>:<EyeOff size={22}/>}</button></header>
  <div className="reels-stage">
  <Swiper onSwiper={s=>{swiper.current=s;}} direction="vertical" modules={[Virtual,Mousewheel,Keyboard,A11y]} virtual a11y={{scrollOnFocus:false}} mousewheel={{forceToAxis:true}} keyboard={{enabled:visible}} onSlideChange={s=>{setActive(s.activeIndex);if(items[s.activeIndex])onSeen(items[s.activeIndex].id);if(s.activeIndex>=items.length-3)setItems(v=>[...v,...shuffle(posts)]);}} className="reels-swiper">{items.map((p,i)=>{const counts=engagement(p,user),video=p.display==='video'&&p.video;return <SwiperSlide key={`${p.id}-${i}`} virtualIndex={i}><div className={`reel-shell ${video?'is-video':''}`} inert={i!==active}>
   {Math.abs(active-i)<=1&&(video?<div className={`video-reel ${p.video?.orientation==='portrait'?'video-reel--portrait':''}`}><VideoPoster post={p} className="reel-loading-poster"/></div>:<FilmPlayer key={`${p.id}-${i}`} post={p} active={active===i&&visible} onAccount={()=>onAccount(p)}/>)}
   {clean&&video&&<div className="reel-swipe-lane swiper-no-swiping" role="group" aria-label="Videolar arasında kaydırma alanı" onPointerDown={e=>{swipeStart.current={x:e.clientX,y:e.clientY};e.currentTarget.setPointerCapture(e.pointerId);}} onPointerUp={e=>{const start=swipeStart.current;swipeStart.current=null;if(!start)return;const dx=e.clientX-start.x,dy=e.clientY-start.y;if(Math.abs(dy)>45&&Math.abs(dy)>Math.abs(dx)*1.5){if(dy<0)swiper.current?.slideNext();else swiper.current?.slidePrev();}}} onPointerCancel={()=>{swipeStart.current=null;}}><i/></div>}
   {!clean&&<div className="reel-actions" aria-label="Gönderi işlemleri"><IconButton label="Reels beğen" active={user.liked.includes(p.id)} onClick={()=>onLike(p.id)}><Heart fill={user.liked.includes(p.id)?'currentColor':'none'}/><span>{formatCount(counts.likes)}</span></IconButton><IconButton label="Reels yorumları" onClick={()=>onComments(p)}><MessageCircle/><span>{counts.comments||''}</span></IconButton><IconButton label="Reels paylaş" onClick={()=>onShare(p)}><Send/><span>{counts.shares?formatCount(counts.shares):''}</span></IconButton><IconButton label={user.saved.includes(p.id)?'Reels koleksiyonlarını düzenle':'Reels kaydet'} active={user.saved.includes(p.id)} onClick={()=>onSave(p.id)}><Bookmark fill={user.saved.includes(p.id)?'currentColor':'none'}/></IconButton><IconButton label="Anlatımı oku" onClick={()=>onOpen(p)}><BookOpen/></IconButton></div>}
  </div></SwiperSlide>;})}</Swiper>
  {lastVideo.current&&<div className="reels-video-dock" aria-hidden={!isVideo} inert={!isVideo}><VideoEmbed post={lastVideo.current} active={!!isVideo&&visible} immersive/></div>}
  </div>
 </div>;
}
