import {useEffect,useMemo,useState} from 'react';
import {ArrowRight,ArrowUpRight,BookmarkCheck,Check,CheckCheck,ChevronLeft,Lightbulb,Play,RotateCcw,Sparkles,Target} from 'lucide-react';
import {Dialog} from './components';
import {PostThumbnail} from './PostDesign';
import {afterDays,applicationPrompt,dailySelection,localDay,recallAnswer,recallPrompt,recordRecall,reviewDue,weeklyActivity} from './learning.mjs';
import type {LearningState,Post} from './types';
import './learning.css';
export function useLocalDay(){const [day,setDay]=useState(localDay);useEffect(()=>{const update=()=>setDay(localDay());const timer=setInterval(update,60000);window.addEventListener('focus',update);return()=>{clearInterval(timer);window.removeEventListener('focus',update);};},[]);return day;}
export function LearningCard({learning,onOpen}:{learning:LearningState;onOpen:()=>void}){
 const day=useLocalDay(),count=learning.days[day]?.length||0,done=count>=learning.goal;
 return <button className={`learning-invitation ${done?'is-complete':''}`} onClick={onOpen}><span className="learning-orbit" style={{'--progress':`${Math.min(1,count/learning.goal)*360}deg`} as React.CSSProperties}>{done?<Check size={24}/>:<Lightbulb size={24}/>}</span><span><small>{done?'BUGÜNKÜ MOLAN TAMAM':'KÜÇÜK BİR ÖĞRENME MOLASI'}</small><strong>{done?'Bugünden aklında bir şey kaldı.':`${learning.goal} keşif. Biraz düşün. Yanına al.`}</strong><span>{count?`${count} keşfi hatırladın`:'Seçkini aç; merak ettiğin yerden başla.'}</span></span><ArrowRight size={20}/></button>;
}
export function LearningHub({posts,learning,onChange,onClose,onWatch,onRecall}:{posts:Post[];learning:LearningState;onChange:(s:LearningState)=>void;onClose:()=>void;onWatch:(p:Post,selection:Post[])=>void;onRecall:(p:Post)=>void}){
 const day=useLocalDay(),[tab,setTab]=useState<'today'|'memory'>('today');
 // Freeze today's selection while the sheet is open so a completed item stays in place.
 const selection=useMemo(()=>dailySelection(posts,learning,day),[posts,day,learning.goal,learning.topic]);
 const due=reviewDue(posts,learning,day),count=learning.days[day]?.length||0,done=count>=learning.goal;
 const topics=['Tümü',...new Set(posts.map(p=>p.category))],week=weeklyActivity(learning,day);
 const notebook=posts.filter(p=>learning.records[p.id]).sort((a,b)=>learning.records[b.id].last.localeCompare(learning.records[a.id].last));
 const minutes=Math.max(1,Math.ceil(selection.reduce((n,p)=>n+(p.video?.duration||p.minutes*60),0)/60));
 return <Dialog title="Öğrenme molan" onClose={onClose}><div className="learning-hub">
  <div className="learning-hero"><span className="eyebrow">MERAKTAN AKLINDA KALANA</span><h2>{done?'Bugünlük güzel bir iz bıraktın.':'Azıcık zaman. Kalıcı bir keşif.'}</h2><p>İzle veya oku. Aklında kalanı anlat. Hayatında bir yer bul.</p><div className="learning-score"><strong>{count}<span> / {learning.goal}</span></strong><span>bugün hatırlanan keşif</span><div className="learning-dots" aria-label={`${count} / ${learning.goal} keşif tamamlandı`}>{Array.from({length:learning.goal},(_,i)=><i key={i} className={i<count?'done':''}>{i<count?<Check size={12}/>:null}</i>)}</div></div>{done&&<p className="learning-celebration" role="status"><CheckCheck size={19}/> Molan tamam. İstersen burada bırak; yarın yine buradayız.</p>}</div>
  <div className="learning-week" aria-label="Son yedi gündeki öğrenme günlerin">{week.map(({day:d,count:c})=><span key={d} className={c?'active':''}><i>{c?<Check size={15}/>:null}</i><small>{new Date(`${d}T12:00:00`).toLocaleDateString('tr-TR',{weekday:'short'})}</small></span>)}</div>
  <div className="learning-tabs" role="tablist" aria-label="Öğrenme alanı"><button role="tab" aria-selected={tab==='today'} onClick={()=>setTab('today')}>Bugünkü seçkim</button><button role="tab" aria-selected={tab==='memory'} onClick={()=>setTab('memory')}>Aklımda kalanlar <small>{notebook.length}</small></button></div>
  {tab==='today'?<><div className="learning-choice"><span><Target size={16}/> Günlük keşif hedefin</span><div>{[3,5,7].map(n=><button key={n} aria-pressed={learning.goal===n} onClick={()=>onChange({...learning,goal:n})}>{n}</button>)}</div></div><div className="learning-topics" aria-label="Öğrenme konusu">{topics.map(t=><button key={t} aria-pressed={learning.topic===t} onClick={()=>onChange({...learning,topic:t})}>{t==='Tümü'?'Karışık seçki':t}</button>)}</div><div className="learning-section-title"><h3>Bugün merak edeceklerin</h3><span>Yaklaşık {minutes} dk + düşünme molası</span></div>{selection.map((p,i)=><div className="learning-post" key={p.id}><button className="learning-thumb" aria-label={`${p.title} keşfini aç`} onClick={()=>onWatch(p,selection)}><PostThumbnail post={p}/><span><Play size={16} fill="currentColor"/></span></button><div><small>{String(i+1).padStart(2,'0')} / {p.category}</small><button className="learning-post-title" onClick={()=>onWatch(p,selection)}>{p.title}</button><button className="learning-recall-link" onClick={()=>onRecall(p)}>{learning.records[p.id]?.last===day?<><Check size={13}/> Notuna bak</>:<>Aklında ne kaldı? <ArrowUpRight size={13}/></>}</button></div></div>)}</>:<><div className="learning-section-title"><h3><RotateCcw size={17}/> Yeniden hatırla</h3><span>{due.length} keşif hazır</span></div>{due.slice(0,7).map((p:Post)=><button className="learning-review" key={p.id} onClick={()=>onRecall(p)}><span><small>{p.category}</small><strong>{p.title}</strong></span><ArrowRight size={18}/></button>)}{!due.length&&<p className="learning-empty">{notebook.length?'Bugün tekrar bekleyen keşfin yok. Yenileri zamanı geldiğinde burada görünecek.':'Henüz bir hatırlama kartın yok. Bir keşfin ardından “Aklımda tut”a dokunarak başlayabilirsin.'}</p>}<div className="learning-section-title"><h3>Hayata taşıdıkların</h3><span>{notebook.filter(p=>learning.records[p.id].applied).length} denendi</span></div>{notebook.map(p=>{const record=learning.records[p.id];return <article className="learning-note" key={p.id}><button onClick={()=>onRecall(p)}><strong>{p.title}</strong><ArrowUpRight size={16}/></button>{record.note&&<p>{record.note}</p>}{record.application&&<blockquote>{record.application}</blockquote>}<footer><span>{record.last===day?'Bugün':record.last.split('-').reverse().join('.')} · tekrar {record.due.split('-').reverse().join('.')}</span><button aria-pressed={record.applied} onClick={()=>onChange({...learning,records:{...learning.records,[p.id]:{...record,applied:!record.applied}}})}>{record.applied?<CheckCheck size={14}/>:<Check size={14}/>} {record.applied?'Denedim':'Hayatta denedim'}</button></footer></article>;})}</>}
  <p className="learning-footnote">İlerleme, kaydırdıklarınla değil hatırlama adımlarınla oluşur. Notların bu cihazda saklanır ve profilindeki yedeğe dahil edilir.</p>
 </div></Dialog>;
}
export function RecallSheet({post,learning,onChange,onClose}:{post:Post;learning:LearningState;onChange:(s:LearningState)=>void;onClose:()=>void}){
 const existing=learning.records[post.id],day=useLocalDay();
 const [note,setNote]=useState(existing?.note||''),[application,setApplication]=useState(existing?.application||''),[revealed,setRevealed]=useState(false),[saved,setSaved]=useState(false),[rating,setRating]=useState<boolean|null>(null);
 const finish=()=>{if(rating===null)return;onChange(recordRecall(learning,post.id,{note:note.trim(),application:application.trim(),remembered:rating},day));setSaved(true);};
 return <Dialog title={saved?'Bir keşif yanına kaldı.':'Aklımda tut'} onClose={onClose}><div className="recall-sheet">{saved?<div className="recall-success"><span><BookmarkCheck size={36}/></span><h2>{rating?'Güzel. Kendi cümlen artık sende.':'Bir kez daha bakmak da öğrenmenin parçası.'}</h2><p>Notun kaydedildi. Sonraki hatırlama: {learning.records[post.id]?.due.split('-').reverse().join('.')}. İstersen bu fikri şimdi gününe taşı.</p>{application&&<blockquote>{application}</blockquote>}<button className="primary-button" onClick={onClose}>Keşfe dön <ArrowRight size={17}/></button></div>:<><small className="eyebrow">{post.category} · 30 SANİYELİK DÜŞÜNME MOLASI</small><h2>{recallPrompt(post)}</h2><label className="recall-label">Aklında kalan<textarea autoComplete="off" maxLength={600} rows={3} value={note} onChange={e=>setNote(e.target.value)} placeholder="Kendi cümlenle… İstersen sesli düşünüp boş bırakabilirsin."/></label>{!revealed?<button className="secondary-button" onClick={()=>setRevealed(true)}>Hatırladım, anlatıma bak <ArrowRight size={16}/></button>:<><div className="recall-answer"><small>ANLATIMI YENİDEN YOKLA</small><p>{recallAnswer(post)}</p><a href={post.sources[0]?.url} target="_blank" rel="noreferrer">Kaynağa bak <ArrowUpRight size={13}/></a></div><fieldset className="recall-rating"><legend>Kendin için değerlendir</legend><button aria-pressed={rating===false} onClick={()=>setRating(false)}><RotateCcw size={16}/> Yeniden bakacağım</button><button aria-pressed={rating===true} onClick={()=>setRating(true)}><Check size={16}/> Hatırladım</button></fieldset><label className="recall-label">Hayatında bir yer bul <small>{applicationPrompt(post)}</small><textarea maxLength={600} rows={2} value={application} onChange={e=>setApplication(e.target.value)} placeholder="Örneğin: Akşam bir arkadaşıma anlatacağım. (İsteğe bağlı)"/></label><button className="primary-button" disabled={rating===null} onClick={finish}>Aklımda tut <BookmarkCheck size={17}/></button></>}</>}</div></Dialog>;
}
