import {createContext,useContext,useEffect,useState,type ReactNode} from 'react';
import {Moon,Sun,Monitor,Focus,Check} from 'lucide-react';
import {defaultPreferences,normalizePreferences} from './preferences.mjs';
export type Preferences={theme:'system'|'light'|'dark';focus:boolean;reveal:'word'|'char';wordSpeed:number;charSpeed:number;textSize:number;narration:boolean;music:boolean;musicVolume:number;savedLayout:'grid'|'list'};
const KEY='learnie-preferences-v1';
const Context=createContext<{prefs:Preferences;setPrefs:(patch:Partial<Preferences>)=>void;dark:boolean;storageError:boolean}>({prefs:defaultPreferences as Preferences,setPrefs:()=>{},dark:false,storageError:false});
export function PreferencesProvider({children}:{children:ReactNode}){
 const [prefs,update]=useState<Preferences>(()=>{try{return normalizePreferences(JSON.parse(localStorage.getItem(KEY)||'{}')) as Preferences;}catch{return defaultPreferences as Preferences;}});
 const [systemDark,setSystemDark]=useState(()=>matchMedia('(prefers-color-scheme: dark)').matches);const [storageError,setStorageError]=useState(false);const dark=prefs.theme==='dark'||(prefs.theme==='system'&&systemDark);
 useEffect(()=>{const media=matchMedia('(prefers-color-scheme: dark)');const change=()=>setSystemDark(media.matches);media.addEventListener('change',change);const storage=(e:StorageEvent)=>{if(e.key===KEY){try{update(normalizePreferences(JSON.parse(e.newValue||'{}')) as Preferences);}catch{}}};window.addEventListener('storage',storage);return()=>{media.removeEventListener('change',change);window.removeEventListener('storage',storage);};},[]);
 useEffect(()=>{document.documentElement.dataset.theme=dark?'dark':'light';document.querySelector('meta[name="theme-color"]')?.setAttribute('content',dark?'#101110':'#fcfcfb');},[dark]);
 const setPrefs=(patch:Partial<Preferences>)=>update(current=>{const next=normalizePreferences({...current,...patch}) as Preferences;try{localStorage.setItem(KEY,JSON.stringify(next));setStorageError(false);}catch{setStorageError(true);}return next;});
 return <Context.Provider value={{prefs,setPrefs,dark,storageError}}>{children}</Context.Provider>;
}
export const usePreferences=()=>useContext(Context);
export function ThemeSettings(){const {prefs,setPrefs}=usePreferences();return <section className="settings-card preference-card"><h2>Görünüm</h2><div className="segmented" aria-label="Tema">{([['light','Açık',Sun],['dark','Koyu',Moon],['system','Sistem',Monitor]] as const).map(([value,label,Icon])=><button key={value} aria-pressed={prefs.theme===value} onClick={()=>setPrefs({theme:value})}><Icon size={17}/>{label}</button>)}</div><p className="preference-note">Seçimin bu cihazda hatırlanır.</p></section>;}
export function FocusSettings({compact=false}:{compact?:boolean}){const {prefs,setPrefs,storageError}=usePreferences();return <div className={`focus-settings ${compact?'compact':''}`}><label className="switch-row"><span><strong><Focus size={17}/> Odak modu</strong><small>Metin seçtiğin ritimde açılsın.</small></span><input type="checkbox" role="switch" aria-label="Odak modu" checked={prefs.focus} onChange={e=>setPrefs({focus:e.target.checked})}/></label><div className="setting-field"><span>Yazı akışı</span><div className="segmented" aria-label="Yazı akışı"><button aria-pressed={prefs.reveal==='word'} onClick={()=>setPrefs({reveal:'word',focus:true})}>Kelime kelime</button><button aria-pressed={prefs.reveal==='char'} onClick={()=>setPrefs({reveal:'char',focus:true})}>Harf harf</button></div></div><label className="setting-field"><span>Hız <output>{prefs.reveal==='word'?`${prefs.wordSpeed} kelime / dk`:`${prefs.charSpeed} harf / sn`}</output></span><input aria-label="Odak hızı" type="range" min={prefs.reveal==='word'?60:5} max={prefs.reveal==='word'?360:40} step={prefs.reveal==='word'?10:1} value={prefs.reveal==='word'?prefs.wordSpeed:prefs.charSpeed} onChange={e=>setPrefs(prefs.reveal==='word'?{wordSpeed:Number(e.target.value)}:{charSpeed:Number(e.target.value)})}/><span className="range-labels"><small>Sakin</small><small>Hızlı</small></span></label><label className="setting-field"><span>Yazı boyutu <output>%{Math.round(prefs.textSize*100)}</output></span><input type="range" aria-label="Odak yazı boyutu" min="0.9" max="1.2" step="0.05" value={prefs.textSize} onChange={e=>setPrefs({textSize:Number(e.target.value)})}/></label><p className="preference-note"><Check size={13}/>{storageError?'Ayarlar bu tarayıcıda saklanamadı.':'Tüm anlatımlar için otomatik kaydedilir.'}</p></div>;}
