import {useMemo,useState} from 'react';
import {Bookmark,BookOpen,Check,Grid2X2,List,Search} from 'lucide-react';
import {Cover,IconButton} from './components';
import {usePreferences} from './Preferences';
import {normalize} from './engine.mjs';
import type {Post,UserState} from './types';
export default function Saved({posts,user,onOpen,onRemove,onRead}:{posts:Post[];user:UserState;onOpen:(p:Post)=>void;onRemove:(id:string)=>void;onRead:(id:string)=>void}){
 const {prefs,setPrefs}=usePreferences();const [query,setQuery]=useState(''),[filter,setFilter]=useState('all');const archive=useMemo(()=>[...user.saved].reverse().map(id=>posts.find(p=>p.id===id)).filter((p):p is Post=>!!p),[posts,user.saved]);const items=archive.filter(p=>(filter==='all'||(filter==='unread'?!user.read.includes(p.id):user.read.includes(p.id)))&&normalize(`${p.title} ${p.category} ${p.subtitle}`).includes(normalize(query)));
 return <><div className="page-title"><span className="eyebrow">SENİN KÜÇÜK ARŞİVİN</span><h1>Bir daha bakarım dediklerin.</h1><p>{archive.length} kayıt · {archive.filter(p=>!user.read.includes(p.id)).length} okumak için bekliyor</p></div><div className="saved-tools"><label className="saved-search"><Search size={17}/><input aria-label="Kaydedilenlerde ara" placeholder="Kayıtlarında ara…" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="saved-layout"><IconButton label="Kayıtları ızgarada göster" active={prefs.savedLayout==='grid'} onClick={()=>setPrefs({savedLayout:'grid'})}><Grid2X2 size={18}/></IconButton><IconButton label="Kayıtları listede göster" active={prefs.savedLayout==='list'} onClick={()=>setPrefs({savedLayout:'list'})}><List size={20}/></IconButton></div></div><div className="saved-filters segmented" aria-label="Okuma durumu">{[['all','Tümü'],['unread','Sonra okuyacağım'],['read','Okuduklarım']].map(([value,label])=><button key={value} aria-pressed={filter===value} onClick={()=>setFilter(value)}>{label}</button>)}</div><div className={`saved-collection ${prefs.savedLayout}`}>{items.map(p=><article className="saved-item" key={p.id}><button className="saved-open" onClick={()=>onOpen(p)}><div className="saved-image"><Cover post={p}/>{user.read.includes(p.id)&&<span className="read-badge"><Check size={13}/> Okundu</span>}</div><div className="saved-copy"><small>{p.category} · {p.minutes} dk</small><h2>{p.title}</h2><p>{p.subtitle}</p></div></button><div className="saved-item-actions"><button onClick={()=>onRead(p.id)}>{user.read.includes(p.id)?<Check size={15}/>:<BookOpen size={15}/>} {user.read.includes(p.id)?'Tekrar okuyacağım':'Okudum'}</button><IconButton label={`${p.title} kaydını kaldır`} onClick={()=>onRemove(p.id)}><Bookmark size={18} fill="currentColor"/></IconButton></div></article>)}</div>{!items.length&&<div className="empty-state"><Bookmark size={32}/><h2>{archive.length?'Burada henüz bir kayıt yok.':'Burası senin merak arşivin.'}</h2><p>{archive.length?'Aramayı veya okuma filtresini değiştirebilirsin.':'Gönderideki yer imine dokun. Sonra okumak istediklerin burada, en yeni kayıt en üstte olacak şekilde birikir.'}</p></div>}</>;
}
