import {PostThumbnail} from './PostDesign';
import {useMemo,useState} from 'react';
import {Bookmark,BookOpen,Check,Grid2X2,List,Search,FolderPlus,Folder,Plus,MoreHorizontal,Trash2,Pencil,X} from 'lucide-react';
import {Cover,IconButton,Dialog} from './components';
import {usePreferences} from './Preferences';
import {normalize} from './engine.mjs';
import {setCollectionMembership} from './collections.mjs';
import type {Post,UserState,Collection} from './types';
export default function Saved({posts,user,onOpen,onRemove,onRead,onCollections}:{posts:Post[];user:UserState;onOpen:(p:Post)=>void;onRemove:(id:string)=>void;onRead:(id:string)=>void;onCollections:(c:Collection[])=>void}){
 const {prefs,setPrefs}=usePreferences();const [query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[collection,setCollection]=useState('all'),[editing,setEditing]=useState<Collection|'new'|null>(null),[name,setName]=useState(''),[assign,setAssign]=useState<Post|null>(null),[deleting,setDeleting]=useState(false),[notice,setNotice]=useState('');
 const archive=useMemo(()=>[...user.saved].reverse().map(id=>posts.find(p=>p.id===id)).filter((p):p is Post=>!!p),[posts,user.saved]);
 const selected=user.collections.find(c=>c.id===collection);const items=archive.filter(p=>(!selected||selected.postIds.includes(p.id))&&(filter==='all'||(filter==='unread'?!user.read.includes(p.id):user.read.includes(p.id)))&&normalize(`${p.title} ${p.category} ${p.subtitle}`).includes(normalize(query)));
 const edit=(c:Collection|'new')=>{setEditing(c);setName(c==='new'?'':c.name);setDeleting(false);setNotice('');};
 const saveCollection=()=>{const trimmed=name.trim();if(!trimmed)return;if(user.collections.some(c=>normalize(c.name)===normalize(trimmed)&&(editing==='new'||c.id!==editing?.id))){setNotice('Bu isimde bir koleksiyonun zaten var.');return;}
  if(editing==='new'){const c={id:crypto.randomUUID(),name:trimmed,postIds:assign?[assign.id]:[],createdAt:new Date().toISOString()};onCollections([...user.collections,c]);if(!assign)setCollection(c.id);}else if(editing)onCollections(user.collections.map(c=>c.id===editing.id?{...c,name:trimmed}:c));setEditing(null);
 };
 return <><div className="page-title saved-title"><span className="eyebrow">SENİN KÜÇÜK ARŞİVİN</span><h1>Bir daha bakarım dediklerin.</h1><p>{archive.length} kayıt · {archive.filter(p=>!user.read.includes(p.id)).length} okumak için bekliyor</p><button className="secondary-button" onClick={()=>edit('new')}><FolderPlus size={17}/> Koleksiyon oluştur</button></div>
 <div className="collection-strip" aria-label="Koleksiyonlar"><button className={`collection-tile ${collection==='all'?'selected':''}`} onClick={()=>setCollection('all')}><span className="collection-cover all"><Bookmark size={27}/></span><strong>Tüm kayıtlar</strong><small>{archive.length} gönderi</small></button>{user.collections.map(c=>{const covers=c.postIds.map(id=>posts.find(p=>p.id===id)).filter((p):p is Post=>!!p).slice(0,4);return <button key={c.id} className={`collection-tile ${collection===c.id?'selected':''}`} onClick={()=>setCollection(c.id)}><span className="collection-cover">{covers.length?covers.map(p=><span className="collection-art" key={p.id}><PostThumbnail post={p}/></span>):<Folder size={27}/>}</span><strong>{c.name}</strong><small>{c.postIds.length} gönderi</small></button>;})}</div>
 {selected&&<div className="collection-heading"><h2>{selected.name}</h2><IconButton label="Koleksiyonu düzenle" onClick={()=>edit(selected)}><MoreHorizontal/></IconButton></div>}
 <div className="saved-tools"><label className="saved-search"><Search size={17}/><input aria-label="Kaydedilenlerde ara" placeholder="Kayıtlarında ara…" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="saved-layout"><IconButton label="Kayıtları ızgarada göster" active={prefs.savedLayout==='grid'} onClick={()=>setPrefs({savedLayout:'grid'})}><Grid2X2 size={18}/></IconButton><IconButton label="Kayıtları listede göster" active={prefs.savedLayout==='list'} onClick={()=>setPrefs({savedLayout:'list'})}><List size={20}/></IconButton></div></div>
 <div className="saved-filters segmented" aria-label="Okuma durumu">{[['all','Tümü'],['unread','Sonra okuyacağım'],['read','Okuduklarım']].map(([value,label])=><button key={value} aria-pressed={filter===value} onClick={()=>setFilter(value)}>{label}</button>)}</div><div className={`saved-collection ${prefs.savedLayout}`}>{items.map(p=><article className="saved-item" key={p.id}><button className="saved-open" onClick={()=>onOpen(p)}><div className="saved-image"><PostThumbnail post={p}/>{user.read.includes(p.id)&&<span className="read-badge"><Check size={13}/> Okundu</span>}</div><div className="saved-copy"><small>{p.category} · {p.minutes} dk</small><h2>{p.title}</h2><p>{p.subtitle}</p></div></button><div className="saved-item-actions"><button onClick={()=>onRead(p.id)}>{user.read.includes(p.id)?<Check size={15}/>:<BookOpen size={15}/>} {user.read.includes(p.id)?'Tekrar okuyacağım':'Okudum'}</button><IconButton label={`${p.title} koleksiyonlarını seç`} onClick={()=>setAssign(p)}><FolderPlus size={18}/></IconButton><IconButton label={`${p.title} kaydını kaldır`} onClick={()=>onRemove(p.id)}><Bookmark size={18} fill="currentColor"/></IconButton></div></article>)}</div>
 {!items.length&&<div className="empty-state"><Bookmark size={32}/><h2>{selected?'Koleksiyonun yeni keşifleri bekliyor.':archive.length?'Bu filtrede kayıt yok.':'Burası senin merak arşivin.'}</h2><p>{selected?'Tüm kayıtlar bölümündeki klasör simgesinden gönderileri buraya ekleyebilirsin.':archive.length?'Aramayı veya okuma filtresini değiştirebilirsin.':'Gönderideki yer imine dokun. Sonra okumak istediklerin burada birikir.'}</p>{selected&&<button className="secondary-button" onClick={()=>setCollection('all')}>Tüm kayıtlara dön</button>}</div>}
 {assign&&<Dialog title="Koleksiyonlara ekle" onClose={()=>setAssign(null)}><div className="collection-picker"><p>{assign.title}</p>{user.collections.map(c=><label className="collection-choice" key={c.id}><Folder size={21}/><span><strong>{c.name}</strong><small>{c.postIds.length} gönderi</small></span><input type="checkbox" aria-label={`${c.name} koleksiyonuna ekle`} checked={c.postIds.includes(assign.id)} onChange={e=>onCollections(setCollectionMembership(user.collections,c.id,assign.id,e.target.checked))}/></label>)}<button className="secondary-button" onClick={()=>edit('new')}><Plus size={17}/> Yeni koleksiyon</button><button className="primary-button" onClick={()=>setAssign(null)}><Check size={17}/> Tamam</button></div></Dialog>}
 {editing&&<Dialog title={editing==='new'?'Yeni koleksiyon':'Koleksiyonu düzenle'} onClose={()=>setEditing(null)}><form className="collection-editor" onSubmit={e=>{e.preventDefault();saveCollection();}}><label className="field-label">Koleksiyon adı<input autoFocus aria-label="Koleksiyon adı" placeholder="Mesela: Aklımda kalsın" maxLength={50} value={name} onChange={e=>setName(e.target.value)}/></label>{notice&&<p role="alert">{notice}</p>}<button className="primary-button" disabled={!name.trim()} type="submit"><Check size={17}/> Kaydet</button>{editing!=='new'&&<>{deleting?<div className="collection-delete"><p>Koleksiyon silinir; gönderiler Tüm kayıtlar bölümünde kalır.</p><button type="button" className="secondary-button" onClick={()=>{onCollections(user.collections.filter(c=>c.id!==editing.id));if(collection===editing.id)setCollection('all');setEditing(null);}}>Koleksiyonu sil</button><button type="button" onClick={()=>setDeleting(false)}>Vazgeç</button></div>:<button type="button" className="delete-collection" onClick={()=>setDeleting(true)}><Trash2 size={16}/> Koleksiyonu sil</button>}</>}</form></Dialog>}
 </>;
}
