import {useEffect,useRef,useState} from 'react';
import {Play,Volume2} from 'lucide-react';
import {usePreferences} from './Preferences';
import {chooseVoice,turkishVoices} from './narration.mjs';
export function useTurkishVoices(){
 const [voices,setVoices]=useState<SpeechSynthesisVoice[]>([]);
 useEffect(()=>{if(!('speechSynthesis'in window))return;const load=()=>setVoices(turkishVoices(speechSynthesis.getVoices()));load();const timer=setTimeout(load,700);speechSynthesis.addEventListener('voiceschanged',load);return()=>{clearTimeout(timer);speechSynthesis.removeEventListener('voiceschanged',load);};},[]);return voices;
}
export default function SpeechSettings({compact=false}:{compact?:boolean}){
 const {prefs,setPrefs}=usePreferences(),voices=useTurkishVoices();const preview=useRef<SpeechSynthesisUtterance|null>(null);const [note,setNote]=useState('');
 useEffect(()=>()=>{if(preview.current)speechSynthesis.cancel();},[]);
 const sample=()=>{const voice=chooseVoice(voices,prefs.voiceURI);if(!voice)return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance('Merhaba. Bugün birlikte yeni bir şey keşfedelim.');u.voice=voice;u.lang='tr-TR';u.rate=prefs.speechRate;u.onend=()=>{preview.current=null;setNote('');};u.onerror=()=>{preview.current=null;setNote('Ses örneği başlayamadı. Yeniden deneyebilirsin.');};preview.current=u;setNote('Ses örneği çalıyor…');speechSynthesis.resume();speechSynthesis.speak(u);};
 return <section className={`speech-settings ${compact?'compact':''}`}><h3><Volume2 size={17}/> Anlatıcı sesi</h3>{!compact&&<label className="switch-row"><span><strong>Türkçe seslendirme</strong><small>Yazılı anlatımları sesli takip et.</small></span><input aria-label="Türkçe seslendirme" type="checkbox" role="switch" disabled={!voices.length} checked={prefs.narration} onChange={e=>setPrefs({narration:e.target.checked})}/></label>}<label className="setting-field"><span>Ses seçimi</span><select aria-label="Anlatıcı sesi" value={voices.some(v=>v.voiceURI===prefs.voiceURI)?prefs.voiceURI:''} onChange={e=>setPrefs({voiceURI:e.target.value})}><option value="">Otomatik · önerilen Türkçe ses</option>{voices.map(v=><option key={v.voiceURI} value={v.voiceURI}>{v.name}</option>)}</select></label><label className="setting-field"><span>Konuşma hızı <output>{prefs.speechRate.toLocaleString('tr-TR')}×</output></span><input aria-label="Konuşma hızı" type="range" min="0.7" max="1.3" step="0.05" value={prefs.speechRate} onChange={e=>setPrefs({speechRate:Number(e.target.value)})}/></label><button className="speech-preview" onClick={sample} disabled={!voices.length}><Play size={16}/> Sesi dinle</button><p className="preference-note">{voices.length?'Bu cihazın sunduğu Türkçe sesler. Seçimin kaydedilir. Seslendirme açıkken yazı konuşmayı takip eder.':'Bu cihazda kullanılabilir Türkçe ses bulunamadı. Cihazının konuşma ayarlarından Türkçe ses ekleyebilirsin.'}</p>{note&&<p role="status" className="preference-note">{note}</p>}</section>;
}
